### ISSUE TITLE
Nightly build refers to orphaned commit 

### ISSUE THREAD

**Issue by MSLaguana** [nodejs/build#850] opened 2017-08-24 16:02 UTC
We try to merge in changes from nodejs/node to nodejs/node-chakracore based on nightly builds from node. As part of that, when trying to bring the payload corresponding to https://nodejs.org/download/nightly/v9.0.0-nightly2017081760f2fa9a8b/ I noticed that the commit hash there, `60f2fa9a8b` or (probably) `60f2fa9a8b050563d2b7f3642a84ff192bd362a6` is not a part of the master branch. I can still find the commit via github, but it isn't a part of my local repo and I can't `git fetch upstream 60f2fa9a8b050563d2b7f3642a84ff192bd362a6` either.

Any idea how this happened? Did the nightly build from a branch other than master, or did master branch rebase/force push at some point?

**Comment by addaleax** [comment] 2017-08-24 16:07
> Any idea how this happened? Did the nightly build from a branch other than master, or did master branch rebase/force push at some point?

Yes – this was me. And yes, it was force-pushed a bit after that commit landed.

The issue was that some of the commits from https://github.com/nodejs/node/pull/14001 were landed in `master` without full metadata (e.g. the parent of said commit nodejs/node@60f2fa9a8b050563d2b7f3642a84ff192bd362a6 had no `PR-URL` or `Reviewed-By` fields), which screws with our tooling for managing releases.

The contents of said commit are identical to the ones of nodejs/node@9e08695f85d4273f01e010cf384f42030d66b453:

```
$ git diff 60f2fa9a8b050563d2b7f3642a84ff192bd362a6 9e08695f85d4273f01e010cf384f42030d66b453|wc
      0       0       0
```

**Comment by joaocgreis** [comment] 2017-08-24 16:11
Also, that nightly is quite old because there were no nightlies for a few days. The problem is now fixed and tonight there should be a new nightly build.

**Comment by MSLaguana** [comment] 2017-08-24 16:11
Great, thanks for that. I'll use the new commit you point out for our pump. Regarding the nightlies being behind: We are operating at a few day delay anyway, so that's not so much of an issue for us.

**Comment by joaocgreis** [comment] 2017-08-29 17:47
I assume this can be closed now, please reopen or let me know if not.

**Closed by joaocgreis** 2017-08-29 17:47 UTC
