### ISSUE TITLE
incident: z/OS hosts down

### ISSUE THREAD

**Issue by refack** [nodejs/build#1465] opened 2018-08-18 20:10 UTC
https://ci.nodejs.org/label/zos-s390x/

@jBarz @mhdawson @nodejs/platform-s390 

P.S. I see we only test `libuv` and not `node`, is that intentional?

**Comment by mhdawson** [comment] 2018-08-22 22:14
@refack we only test libuv as we don't have all of the contributions required for Node.js yet.  Still working on that.

Just back from vacation.  See nobody else chimed in, thats because @jBarz left IBM and we still need to get somebody else into zos-s390x

**Comment by mhdawson** [comment] 2018-08-22 22:14
@gdams can you chase what's going on here and add yourself to platform-s390.

**Comment by gdams** [comment] 2018-08-24 17:47
okay so here's the steps to bring the machines back online:

```bash
ssh unix1@<zos_host>
sh /u/iojs/start.sh
```

**Comment by gdams** [comment] 2018-08-24 17:51
test build looking good: https://ci.nodejs.org/job/libuv-test-commit-zos/nodes=zos-s390x/938/console

**Comment by refack** [comment] 2018-09-13 13:52
FTR: the default shell does not recognize `su - -s iojs`, but `bash` does.

**Comment by joaocgreis** [comment] 2019-06-25 15:21
@mhdawson @sam-github All z/OS hosts were down, with a few libuv jobs queued up. I brought them back using the instructions above, but all of the builds that were queued turned red. Possibly because of some missing configuration.
- https://ci.nodejs.org/computer/test-marist-zos13-s390x-1/builds
- https://ci.nodejs.org/computer/test-marist-zos13-s390x-2/builds

**Comment by sam-github** [comment] 2019-06-25 15:30
Hm, kicked off another build: https://ci.nodejs.org/job/libuv-test-commit-zos/1693/

**Comment by sam-github** [comment] 2019-06-25 15:50
I'd prefer we close this issue and open another, since it doesn't seem related - I'd rather not have a floating issue per host type that gets reopened whenever that host is down.

@nodejs/platform-s390 would you agree? Shall I open another to track this latest issue, which seems it may be caused by the python updates (though that's still being looked into)?

**Comment by mhdawson** [comment] 2019-06-25 17:43
@joaocgreis thanks for pointing this out. I had noticed earlier today when I got emails saying all those jobs failed. I had wondered why I just got them today, but makes sense if they were queued.  @sam-github is following up on this issue.

@sam-github I agree a new issue makes sense to me.

**Comment by sam-github** [comment] 2019-06-26 02:02
new issue, for new problem: https://github.com/nodejs/build/issues/1855

**Closed by sam-github** 2019-06-26 02:02 UTC
Labels: incident
