### ISSUE TITLE
RHEL/s390x machine failure in citgm

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1610] opened 2018-11-29 06:15 UTC
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1655/nodes=rhel72-s390x/console

**Comment by Trott** [comment] 2018-11-29 18:32
(Might want to copy/paste the relevant stuff into this issue because the CI link will go stale and then no one will know what this issue was about.)

**Comment by richardlau** [comment] 2018-11-29 19:02
> 
> 
> (Might want to copy/paste the relevant stuff into this issue because the CI link will go stale and then no one will know what this issue was about.)

 
> https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1655/nodes=rhel72-s390x/console

```
01:13:16 make[1]: Leaving directory `/data/iojs/build/workspace/citgm-smoker/nodes/rhel72-s390x/node/out'
01:13:16 if [ ! -r node -o ! -L node ]; then ln -fs out/Release/node node; fi
01:13:16 /usr/bin/python tools/install.py install '' '/data/iojs/build/workspace/citgm-smoker/nodes/rhel72-s390x/smoker'
01:13:16 installing /data/iojs/build/workspace/citgm-smoker/nodes/rhel72-s390x/smoker/bin/node
01:13:16 installing /data/iojs/build/workspace/citgm-smoker/nodes/rhel72-s390x/smoker/share/systemtap/tapset/node.stp
...
01:13:17 installing /data/iojs/build/workspace/citgm-smoker/nodes/rhel72-s390x/smoker/lib/node_modules/npm/node_modules/iconv-lite/lib/bom-handling.js
01:13:17 installing /data/iojs/build/workspace/citgm-smoker/nodes/rhel72-s390x/smoker/lib/node_modules/npm/node_modules/iconv-lite/lib/index.js
01:13:17 installing /data/iojs/build/workspace/citgm-smoker/nodes/rTraceback (most recent call last):
01:13:17   File "tools/install.py", line 225, in <module>
01:13:17     run(sys.argv[:])
01:13:17   File "tools/install.py", line 219, in run
01:13:17     if cmd == 'install': return files(install)
01:13:17   File "tools/install.py", line 155, in files
01:13:17     if 'true' == variables.get('node_install_npm'): npm_files(action)
01:13:17   File "tools/install.py", line 89, in npm_files
01:13:17     action(paths, target_path + dirname[9:] + '/')
01:13:17   File "tools/install.py", line 74, in install
01:13:17     def install(paths, dst): map(lambda path: try_copy(path, dst), paths)
01:13:17   File "tools/install.py", line 74, in <lambda>
01:13:17     def install(paths, dst): map(lambda path: try_copy(path, dst), paths)
01:13:17   File "tools/install.py", line 63, in try_copy
01:13:17     print 'installing %s' % target_path
01:13:17 IOError: [Errno 11] Resource temporarily unavailable
01:13:17 make: *** [install] Error 1
01:13:17 Build step 'Conditional steps (multiple)' marked build as failure
```

**Comment by rvagg** [comment] 2018-11-30 01:08
> `IOError: [Errno 11] Resource temporarily unavailable`

I wonder if this is that stdout contention problem that make seems to have with parallelism? If so it should be flaky, but maybe it's s390x specific.

**Comment by gdams** [comment] 2019-01-09 15:36
I don't seem to be able to reproduce this failure. Has anyone made any changes already?

**Comment by gdams** [comment] 2019-02-05 14:39
@bethgriggs has run CITGM a handful of times and not observed this error. Closing

**Closed by gdams** 2019-02-05 14:39 UTC
