### ISSUE TITLE
release-orka-macos11-x64-1 git issue

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3419] opened 2023-07-11 14:56 UTC
https://ci-release.nodejs.org/job/iojs+release/9489/nodes=osx11-x64-release-tar/console
```console
15:45:48 stderr: Executable requires at least macOS 12.0, but is being run on macOS 11.6, and so is exiting.
```

Looks like it's `git`:
```console
administrator@release-orka-macos11-x64-1 ~ % git
Executable requires at least macOS 12.0, but is being run on macOS 11.6, and so is exiting.
administrator@release-orka-macos11-x64-1 ~ %
```

The machine was rebuilt today (https://github.com/nodejs/build/issues/3416).

cc @UlisesGascon

**Comment by UlisesGascon** [comment] 2023-07-11 16:54
I am on it, I will confirm when the correct version is installed

**Comment by UlisesGascon** [comment] 2023-07-11 17:12
Patched, I will monitor the jobs and then close the issue

**Comment by targos** [comment] 2023-07-11 17:16
Do you know how the wrong version got installed?

**Comment by UlisesGascon** [comment] 2023-07-12 07:06
> Do you know how the wrong version got installed?

Yes, I was following the manual steps after re-ansible the machine and I installed the wrong version manually. I replaced it already.

**Comment by UlisesGascon** [comment] 2023-07-12 07:10
I see an error now for cloning the repo:

```
08:10:12 ERROR: Timeout after 10 minutes
08:10:13 ERROR: Error cloning remote repo 'origin'
```

But it is not related to Xcode (as before), [Full details](https://ci-release.nodejs.org/job/iojs+release/nodes=osx11-x64-release-tar/lastBuild/console)

**Comment by UlisesGascon** [comment] 2023-07-12 07:14
git should be working by now 👍

**Comment by UlisesGascon** [comment] 2023-07-12 07:40
> What about xcodebuild --version ?

```
administrator@release-orka-macos11-x64-1 ~ % xcodebuild -version
Xcode 13.2.1
Build version 13C100
```

**Comment by UlisesGascon** [comment] 2023-07-12 15:20
[last build passed](https://ci-release.nodejs.org/job/iojs+release/), so I close the issue now

**Comment by targos** [comment] 2023-12-18 15:44
Reopening because the machine is in a weird state. It doesn't seem to have Xcode installed:

```
% xcodebuild -version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

I think this is the cause of build issues with V8 canary: https://ci-release.nodejs.org/job/iojs+release/9842/nodes=osx11-x64-release-tar/console

**Comment by UlisesGascon** [comment] 2024-02-26 15:41
This was solved when we regenerated the release machine in https://github.com/nodejs/build/issues/3616. So I will close the issue now, but feel free to reopen if we detect more issues again.

**Closed by UlisesGascon** 2024-02-26 15:41 UTC
Labels: platform:osx, ci-release
