### ISSUE TITLE
jenkins-workspace-1 cross-compile ssh-agent zombies

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#1566] opened 2018-11-07 09:12 UTC
maybe not technically zombies, but we've observed this before and it becomes a problem after build-up:

```
root@test-packetnet-ubuntu1604-x64-1:~# ps auxww | grep ssh-agent | wc
    675    7427   50643
```

From https://ci.nodejs.org/job/node-cross-compile/19441/nodes=cross-compiler-armv6-gcc-4.9.4/console:

```
+ git push binary_tmp@147.75.70.237:binary_tmp.git +jenkins-node-test-commit-arm-fanned-ce84f1ae17ba2fc810ecaf7573e212c58320fedd-binary-pi1p/cc-armv6
ssh: connect to host 147.75.70.237 port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I'm going to take the machine down when and restart & clean it up but this is going to happen again before long.

@joaocgreis any ideas off the top of your head before I dive in and figure it out myself?

**Comment by rvagg** [comment] 2018-11-07 09:14
fwiw I don't know if the cross-compile `git push` is to blame here of it's just hitting ssh limits on that machine caused by other things that happen on that machine. jenkins-workspace-2 doesn't have any ssh-agent processes running on it so I'm assuming it is to do with cross-compiling and connections not being cleaned up or something.

**Comment by rvagg** [comment] 2018-11-07 09:15
oh, also, just to confuse matters, all of these ssh-agent processes are running as user `iojs`, not `binary_tmp` which is the user the cross-compiler uses 🤷‍♂️

**Comment by joaocgreis** [comment] 2018-11-07 16:33
Multi-configuration jobs like `node-cross-compile` have two parts: the "base job" that runs on `jenkins-workspace`, and one for each configuration that runs on the workers. The actual `git push` runs on the workers, but for some reason Jenkins also launches a ssh-agent on the workspace. In [the link you sent above](https://ci.nodejs.org/job/node-cross-compile/19441/nodes=cross-compiler-armv6-gcc-4.9.4/console), I see the agent being stopped in the last few lines. However, looking at the console output for the workspace for the same job in https://ci.nodejs.org/job/node-cross-compile/19441/console , I see the agent being started but not stopped.

The `binary_tmp` user is only necessary to have a dedicated git shell in the server, there should be nothing else running as that user. Everything Jenkins should run as `iojs`.

So, this is probably the workspace part of a job. Now we have to get the job (or jobs) right. `node-cross-compile` is a good candidate because of the above, but here's the full list of them:
```
git-clean-tmp-repo
git-delete-branches
git-nodesource-update-reference
git-nodesource-update-reference
git-nodesource-update-reference
git-rebase
git-rebase
libuv-in-node
node-cross-compile
node-stress-single-test-pi1-binary
node-stress-single-test-pi1-binary
node-test-binary-arm
node-test-binary-arm
node-test-binary-arm-OLD
node-test-binary-arm-OLD
```

One possible hackish workaround for this is just to add a kill command to cron in the workspaces. This should not be a problem because ssh-agent should not be needed for anything in those servers.

**Comment by rvagg** [comment] 2018-11-07 22:46
cron to kill was my first thought but seemed hackish.

This should kill `ssh-agent` processes that are older than a day:

```
ps -eo comm,pid,etime | grep -E '^java\s.*\s[0-9]+-([0-9]{2}:?){3}$' | awk '{print $2}' | xargs -rl kill
```

I'll get this into cron and see what it does.

The odd thing here though is that it's only jenkins-workspace-1 that's filling up with these, jenkins-workspace-2 is fine.

**Comment by rvagg** [comment] 2018-11-08 13:14
@joaocgreis:

```
$ du -sh /home/iojs/build/binary_tmp.git
105G	/home/iojs/build/binary_tmp.git
```

This is causing timeout problems between the cross compilers and jenkins-workspace-1. How do we prune this repo and what can we put in crontab to do it regularly?

**Comment by joaocgreis** [comment] 2018-11-08 20:48
> The odd thing here though is that it's only jenkins-workspace-1 that's filling up with these, jenkins-workspace-2 is fine.

When starting a job, Jenkins seems to prefer to run it in a worker where it has been run before. So this might be caused by something that happens to only run in `jenkins-workspace-1`.

> How do we prune this repo and what can we put in crontab to do it regularly?

PR here: https://github.com/nodejs/build/pull/1515 . I have to land that and do a few other items that are left over from keeping the binaries. I kept it open for monitoring, since we keep the binaries for 1  month I expected the size to stabilize by now, but looks like it is a bit too much. We can run the cron job daily instead of weekly, and if that doesn't work we can reduce the time to 3 weeks.

For quick reference, here is how to clean it manually:
```
ssh jenkins-workspace-1
su binary_tmp -s /bin/bash
cd ~/binary_tmp.git
du -sh .
git prune
du -sh .
```

**Comment by joaocgreis** [comment] 2018-12-01 02:52
Confirmed this comes from the workspace part of `node-cross-compile`.

Changed the job to not use the Jenkins ssh-agent, but one in each line similar to other jobs: https://ci.nodejs.org/job/node-cross-compile/jobConfigHistory/showDiffFiles?timestamp1=2018-11-30_21-21-42&timestamp2=2018-11-30_21-35-27 . I don't think we have any other "multi-configuration" type job using ssh-agent, but if we ever need one it should be done this way.

Had to change the git credentials back to the iojs key used by the temp repo, it was `node-private`. The error I got was similar to the one in the opening comment, so this was possibly the issue all along. I suspect this worked most of the times because the ssh-agent was started with the right credentials, and Jenkins does that before running git.

Server looks clean after running test jobs, I'll close this.

**Closed by joaocgreis** 2018-12-01 02:52 UTC
