### ISSUE TITLE
Downloading node is super slow

### ISSUE THREAD

**Issue by SimenB** [nodejs/build#562] opened 2016-12-09 13:04 UTC
X-post: nodejs/nodejs.org#1061

Our builds are currently failing because of this. Sorry if it's the wrong repo

**Comment by EloB** [comment] 2016-12-09 13:10
I've tried to reinstall node and now I can't work because if this :(

**Comment by SimenB** [comment] 2016-12-09 13:11
It usually completes in the end

**Comment by jbergstroem** [comment] 2016-12-09 13:36
I'll have a look and see if something is up with cloudflare/digitalocean.

**Comment by EloB** [comment] 2016-12-09 13:43
@jbergstroem https://www.cloudflarestatus.com/ they have problem.

**Comment by SimenB** [comment] 2016-12-09 13:45
Either this or nodejs/nodejs.org#1061 should probably be closed, to keep it in one place 😄

**Comment by targos** [comment] 2016-12-09 13:47
Not sure it's a cloudflare issue. This is the error I get:

![screenshot from 2016-12-09 14-44-53](https://cloud.githubusercontent.com/assets/2352663/21050965/2a1fdc92-be1e-11e6-8355-98caa7a3af73.png)

**Comment by SimenB** [comment] 2016-12-09 13:48
I did get some TLS errors initially, before it just plain timed out

**Comment by PeterDaveHello** [comment] 2016-12-09 13:52
I wonder if there is any chance that we can build/provide mirror service in case we have some familiar problem again?

**Comment by jbergstroem** [comment] 2016-12-09 13:54
Traffic is within 5% of what we can expect around this time of day. I didn't see any out of the ordinary errors in our nginx error log and our ssl certs are valid.

**Comment by agsmorodin** [comment] 2016-12-09 13:54
Issue still exists. 
Here is my speed now, Amsterdam location:
```
wget https://nodejs.org/dist/v0.12.2/node-v0.12.2-linux-x64.tar.gz
--2016-12-09 13:43:57--  https://nodejs.org/dist/v0.12.2/node-v0.12.2-linux-x64.tar.gz
Resolving nodejs.org (nodejs.org)... 104.20.22.46, 104.20.23.46, 2400:cb00:2048:1::6814:162e, ...
Connecting to nodejs.org (nodejs.org)|104.20.22.46|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9487774 (9.0M) [application/gzip]
Saving to: 'node-v0.12.2-linux-x64.tar.gz.5

 6% [=========>                                                                                                                                                         ] 638,731     14.6KB/s   in 3m 5s  

2016-12-09 13:47:11 (3.36 KB/s) - Connection closed at byte 638731. Retrying.

--2016-12-09 13:47:12--  (try: 2)  https://nodejs.org/dist/v0.12.2/node-v0.12.2-linux-x64.tar.gz
Connecting to nodejs.org (nodejs.org)|104.20.22.46|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 9487774 (9.0M), 8849043 (8.4M) remaining [application/gzip]
Saving to: 'node-v0.12.2-linux-x64.tar.gz.5
1,539,008   5.44KB/s  eta 43m 48s^C
```

**Comment by jbergstroem** [comment] 2016-12-09 13:55
(I'm not saying we're not experiencing issues, just taking notes from what I can measure)

**Comment by malaire** [comment] 2016-12-09 13:57
Same problem when downloading from Finland -- all larger (few MB or more) downloads fail with Partial Content.

**Comment by jbergstroem** [comment] 2016-12-09 14:04
I'm getting pretty awful packet loss to the origin host; investigating.

**Comment by mhdawson** [comment] 2016-12-09 14:09
I can confirm that even just trying to load benchmarking.nodejs.org is taking a really long time from Ottawa/Canada

**Comment by jbergstroem** [comment] 2016-12-09 14:19
Definitely something going on at our host. I've gotten in touch with support but will try to debug as much as possible (which as you know is a great experience over ssh with packet loss).

**Comment by bennyn** [comment] 2016-12-09 15:17
I saw that Travis is downloading Node.js versions via `nvm`. Even if they are pre-installed on the VM.

Here is what is preinstalled (Build system information):

![preinstalled](https://cloud.githubusercontent.com/assets/469989/21053587/57173702-be2a-11e6-9b42-412a1eeff739.PNG)

Here is the log entry from `nvm`:

![image](https://cloud.githubusercontent.com/assets/469989/21053664/c2bfb5ec-be2a-11e6-8c64-74092f01c40c.png)

I don't know why it's doing that (downloading Node.js v6.9.1 again) because we have set an explicit version (which should be pre-installed) in our `.travis.yml`:

```yml
language: node_js
node_js:
  - 6.9.1
```

Build Log: 
- https://travis-ci.org/wireapp/wire-webapp/builds/182614458

**Comment by PeterDaveHello** [comment] 2016-12-09 15:19
@bennyn I think `nvm` shows the reason as the checksum not matched.

**Comment by PeterDaveHello** [comment] 2016-12-09 15:20
@jbergstroem is there any chance to provide an alternative or mirror site so that we can tolerance the problem until it's fixed? Thanks.

**Comment by jbergstroem** [comment] 2016-12-09 15:26
@PeterDaveHello you can try using http://unencrypted.nodejs.org. It is a mirror but shouldn't be treated as such when nodejs.org is unavailable (read: this is not the official mirror, just an unencrypted version for old http clients)

**Comment by jbergstroem** [comment] 2016-12-09 15:27
Update: The issue is identified, I'm working with DO support to resolve it.

**Comment by matthewp** [comment] 2016-12-09 15:30
There's a second issue I think should be addressed. If a `.travis.yml` has a Node version set as `4` or `7` or whatever else and the download fails, Travis shouldn't continue on defaulting to 0.10 as it currently is doing. It should fail immediately, as it can't build what the user intended.

**Comment by SimenB** [comment] 2016-12-09 15:33
@matthewp that's an issue with travis, or maybe nvm. Not nodejs.org

**Comment by matthewp** [comment] 2016-12-09 15:33
Correct! Sorry for the noise.

**Comment by PeterDaveHello** [comment] 2016-12-09 15:53
@jbergstroem thanks for helping.

I thought http://unencrypted.nodejs.org/ really looks like an official mirror since it's under nodejs.org, it'll be great if we could have rsync protocol so that people can easily create mirrors, especially inside enterprise or the area with limited network access.

**Comment by glasser** [comment] 2016-12-09 15:54
unencrypted.nodejs.org doesn't appear to have 4.6.1 or 4.6.2.

Are there any mirrors?

**Comment by PeterDaveHello** [comment] 2016-12-09 15:54
@jbergstroem btw, http://unencrypted.nodejs.org/ looks out-dated?

**Comment by PeterDaveHello** [comment] 2016-12-09 15:55
@glasser if you need nodejs v4.6.2 linux binary build, I can help.

**Comment by jbergstroem** [comment] 2016-12-09 16:01
@PeterDaveHello ouch. I'm updating it now -- give it a few minutes.

**Comment by PeterDaveHello** [comment] 2016-12-09 16:02
@jbergstroem is it possible to provide an official method to mirror it?

**Comment by jbergstroem** [comment] 2016-12-09 16:02
@PeterDaveHello unencrypted.nodejs.org is in preparations of being both a http and rsync mirror. We will officially announce it when done.

**Comment by PeterDaveHello** [comment] 2016-12-09 16:03
@jbergstroem that's awesome, thanks for the info!

**Comment by bear** [comment] 2016-12-09 16:03
@jbergstroem CircleCI SRE/Ops person here ... after you have recovered from the event please do reach out to me (us) if we can be of any assistance with mirrors

**Comment by jbergstroem** [comment] 2016-12-09 16:04
Progress update: we will have to move the origin host to finally resolve the network issues. Should not take more than 20 minutes.

**Comment by PeterDaveHello** [comment] 2016-12-09 16:07
@bear it'll be good to have a local mirror inside Circle CI 👍

**Comment by jbergstroem** [comment] 2016-12-09 16:12
@bear: thanks for reaching out.

For those of you that are interested in mirroring; `unencrypted.nodejs.org` will provide both rsync and http endpoints in a not-too-far future. We will announce this as part of migratating nodejs.org to enforce HSTS (and ssl only).

**Comment by jbergstroem** [comment] 2016-12-09 16:29
20 minutes has passed, so another update: Host is back up; we're still working with support to resolve networking issues - but hopefully this'll come to an end very shortly.

**Comment by jbergstroem** [comment] 2016-12-09 16:53
Update: we're back and catching up. I will keep a close look at performance and will finally close issues once everything is back. Expect a followup blog post / issue once we've collected all information.

**Comment by mikeal** [comment] 2016-12-09 18:25
I wonder if there are some Cloudflare settings we can use to make the caching more aggressive and not run into this in the future.

For our downloads, all of the content is "append only" right? We never replace resources that we put up there so we could make the caching super aggressive.

/cc @terinjokes

**Comment by dragon788** [comment] 2016-12-09 18:35
@jbergstroem You should check out Mosh, https://mosh.org/. At least that way your ssh session will feel responsive instead of utter tripe when on an unreliable connection.

**Comment by jbergstroem** [comment] 2016-12-09 18:40
@mikeal: there's a few things we can do to improve a situation where our origin runs into availability issues:
1. change the way we generate http logs so we can have cloudflare face all downloads. this requires a few things, most importantly changing our account type at cf
2. set up a different ruleset for all downloads throuh cloudflare and add redundancy, for instance from `unencrypted.nodejs.org` once that treated as official.
3. further explore distributed mirrors and organize them similarly to how other operating system/package managers works. 

@mikeal you're correct -- each node.js artifact is treated as read-only once generated (we have checksums for all of them), which means that cf could fully front us once 1. above is accomplished.

**Comment by jbergstroem** [comment] 2016-12-09 18:43
Going to close this issue now, since we've resolved all outstanding issues. Please let us know if you find anything not working. Thanks for having patience with us!

**Closed by jbergstroem** 2016-12-09 18:43 UTC

**Comment by mikeal** [comment] 2016-12-09 18:55
> changing our account type at cf

Which account type would we need? I thought we had a comp'd enterprise account?

**Comment by jbergstroem** [comment] 2016-12-09 18:57
@mikeal: it used to be enterprise, now is business.

**Comment by terinjokes** [comment] 2016-12-09 20:53
@mikeal I'm happy to chat with you offline and see what we can do.

**Comment by soberstadt** [comment] 2016-12-12 14:16
Thank you for your hard work! It was a pretty minor inconvenience for me, my Travis builds were not working during the downtime. I assuming that most others were experiencing simular pain. Moving forward, I added this to my .travis.yml file to cache my node version to avoid the build dependency:
```
cache:
  directories:
    - node_modules
    - ../../../.nvm/versions
```

**Comment by mikeal** [comment] 2016-12-12 21:43
I spoke with Terin about this. With our current account there are more aggressive caching rules we can set. @terinjokes can give use the exact syntax.

**Comment by jbergstroem** [comment] 2016-12-13 01:02
@terinjokes perhaps drop by our irc channel and have a chat? I'm jbergstroem@freenode, channel is #node-build.

**Comment by jbergstroem** [comment] 2016-12-13 01:53
@mikeal see my comment above as why we don't cache "everything".

**Comment by PeterDaveHello** [comment] 2017-04-09 08:44
@jbergstroem Hi! do you still plan to provide official mirror mechanism? since nodejs.org was down again few days ago and I don't know if there is any ETA on it, I can only use other stupid method to mirror it right now, to prevent the next server down and provide better performance 😉

To those who needs a mirror, you can try: http://ftp.yzu.edu.tw/nodejs.org-dist,
and export to environment variable for node version manager ✨  
```sh
export NVM_NODEJS_ORG_MIRROR="http://ftp.yzu.edu.tw/nodejs.org-dist"
```

**Comment by jbergstroem** [comment] 2017-04-09 18:21
@PeterDaveHello it's not gone; its mirrored at http://unencrypted.nodejs.org/download/. The landing page I created to say it was unencrypted was temporarily 404'ing (not sure we should even keep it).

**Comment by mohamedalighouma** [comment] 2018-08-09 19:40
the same here
