### ISSUE TITLE
AIX build resources

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#237] opened 2015-11-05 23:33 UTC
There's a lot of changes making their way into core where only IBM folks are able to make a judgement on their appropriateness because the rest of us don't have the ability to run them on AIX. I'm concerned about creating a dark corner in both our code and in our community of collaborators because of this division.

What are the barriers to being able to hook up an AIX machine to Jenkins for testing? We have the PPC Linux boxes there from IBM, is it a big reach to also include AIX in the mix?

/cc @mhdawson @jasnell

**Comment by jasnell** [comment] 2015-11-06 00:02
I'll follow up on the progress on this side. I'll get back to you.

**Comment by mhdawson** [comment] 2015-11-06 14:10
I've been trying hard to get AIX machines.  The problem is that it has not been common practice up to this point to provide AIX machines to OS projects so there is no existing mechanism/pattern to draw on. 

I've been talking to different groups within IBM to see if I can find one that will be able to fund/provide the machines.  There is support but the best I've been able to do so far would likely result in machines in the first half of next year.  I'm still pushing to see if we can find a more immediate solution.

**Comment by jbergstroem** [comment] 2015-11-09 12:06
I think its great that we're getting improved coverage and test runs for AIX but the lack of third party review is unfortunate.

**Comment by mhdawson** [comment] 2015-12-02 17:23
Internal discussions (at IBM) have landed on a plan which would hopefully end up with machines being available end of Jan timeframe.  I'm still working to see if we can find any options to bridge the gap between now and then.

**Comment by mhdawson** [comment] 2016-01-29 21:17
Ok so still working on the long term solution to get a machine to osuosl that can host AIX VM's, however the AIX team has provided me with a temporary vm (1-2 month) through siteox that I can connect up and allow people to log into in cases where they want to run/test on AIX.

Will start looking at getting it hooked up.

**Comment by mhdawson** [comment] 2016-02-04 21:41
PR to add changes for ansible config https://github.com/nodejs/build/pull/323
Running builds on machine which has been added: https://ci.nodejs.org/job/node-test-commit-aix/33/

This is a temporary machine until we get longer term resources from osuosl and there are a few issues

1) smallish machine.  

2) I had to limit build to 1 cpu because otherwise I saw failures with "directly already exists" in the v8 part of the build.  One suggestion was there may be some code doing a mkdir -p with out allowing for the already existing case.  I'll have to investigate this one further as our internal (IBM) builds don't suffer from this although we don't use the same run-ci target.

I don't seem to have ssh keys working yet.  So far I have done ssh into the box using the password provided.  It is some kind of shared resource at siteox.com but not sure if that is related (we do have to use a specific ssh port and each server seems to get its own port).

3) I don't have ccache enable.  Will have to see what you need to do for that on AIX. 

4) the combination of a few of the above means that the build currently takes ~ 1hr 49 min so we can't add to the standard regression test.  I'll look at setting up a daily run for how.

5) There are some failures in the CI run, I have opened new issues for them.  


At this point I think we are at least in the state where we can give people access to the machine to debug/review when necessary.  I don't necessarily want try and resolve all of these until we get the full h/w horsepower from osuosl (which is waiting on us getting them a new AIX box).

I'd suggest we close this issue and I can open a new one to track completion on the issues mentioned.

**Comment by mhdawson** [comment] 2016-02-16 20:36
Closing let me know if anybody else disagrees

**Closed** 2016-02-16 20:53 UTC
