### ISSUE TITLE
postmortem for downloads incident

### ISSUE THREAD

**Issue by Trott** [nodejs/build#3231] opened 2023-03-16 19:32 UTC
Once resolved, we should probably do a postmortem on https://status.nodejs.org/incidents/svk1f6czgxy6.

Suggested in Slack by @ovflowd

**Comment by MattIPv4** [comment] 2023-03-16 22:58
Status page has the ability to publish a post-mortem directly on the incident, and I whole-heartedly agree it'd make sense to publish one here.

In terms of structure, I think it should probably be a few sentences about the incident, what went wrong, and what eventually fixed it. Maybe a bit that touches on why the incident was so long, and future plans to prevent the same thing again.

After that, it'd be helpful to have a high-level timeline of the whole incident, as the status page only captures updates for the last few hours once I was looped in.

@ovflowd (or others), it'd be great to get a rough timeline of when the problem started and the initial steps taken etc. (I wasn't there at the start). I'm happy to help with the timeline after that (others are also welcome to write that out too). I'm guessing Slack threads will be a good source of timestamps for everything.

**Comment by MattIPv4** [comment] 2023-03-16 23:47
Draft:

# The Incident

Starting on March 15th and going into March 16th, users were receiving intermittent 404 responses when trying to download Node.js from nodejs.org, or even accessing parts of the website.

What surfaced as one issue, users seeing 404s, was actually the result of multiple compounding issues all happening at once:

- The Cloudflare config for nodejs.org had multiple Page Rules configured with "Cache Everything" enabled alongside "Browser/Edge Cache TTLs" being set. This resulted in any 404 responses from the origin server being cached by Cloudflare.

- The origin server for nodejs.org was being overloaded, and due to a recent configuration change, was now erroneously returning 404 responses for valid files when it was overloaded and couldn't read them from its disk.

- A build script bug caused by the recent migration of the website to Next.js had resulted in the site being rebuilt and the entire Cloudflare cache being purged every five minutes, sending an abnormally high number of requests to the origin server and putting it under excessive load.

Together, these compounded together to result in the origins server receiving far more requests than normal, failing to read files from its disk that existed, returning incorrect 404 responses, and Cloudflare then caching those 404s.

A large team came together to investigate this issue, with the full fix being put in place at approximately 8PM UTC on the 16th. Many of the Cloudflare Page Rules that had been removed as part of this fix (that were causing the 404s to be cached) had cache TTLs for four hours, and so the full impact of this incident was not resolved until 12AM UTC on the 17th.

Related to the 404s users were receiving, it was also discovered that requests to localised pages on nodejs.org weren't resolving as expected when a localised version didn't exist. Instead of falling back to the English version of the pages, they were returning a 404. A secondary update was made to the NGINX config for nodejs.org at approximately <insert time> on the 17th that fixed this.

## Details

<insert more technical details on what caused this, and the fix that was put in place for each of the issues>

## Timeline

<insert high level timeline of detection, triage, fix, etc.>

**Comment by ovflowd** [comment] 2023-03-17 00:07
Worth to mention that part of the 404 issue was due that we made a fundamental change how not found pages were handled. 

- Actual 404s were not technically being handled as 404s, actually internally being handled as server errors that would stack over time and cause a crit. This is because no try_files were being used, meaning nginx would attempt a direct fs open() request without actually handling gracefully if a file doesn't exist.
- Over time these would cause 5XXs errors. For obvious reasons, Cloudflare doesn't cache Server Errors.
- Recent changes corrected this bug that was crashing and slowing the server, by properly handling the requests with try_files and gracefully handle them as 404s.
- Cloudflare then started to cache these files, meaning, instead of a very small subset of origin requests with 5XX we would now have a larger subset of cached 404s being delivered over the network.
- This also coincided with the fact that the cache was being purged every 5 minutes and that the current nginx directives were unoptimised and there was a lot of redundancy, which also clashes with recent nginx changes for redirection.
- Around the 16th afternoon, we were deploying nginx rewrite fixes as we initially thought that the problem was on the way how we handle try_files actually not being able to match the binaries within the /dist folder.
- During the meantime, in an effort (attempt) to fix the issue that (we also spotted) the Website 404 page was not being used as the 404 page was now under a new path /en/404/index.html instead of /en/404.html within the static generated pages, we made a deployment to fix the wrong 404 page (default Next.js one) from being served.
- We've noticed that by fixing that, GitHub Pages would not recognise the 404 page anymore, as it requires a root 404.html. We then proceeded to disable a feature from Next.js (trailingSlashes) so that each path would be its own file. So /en/ would be en.html instead of /en/index.html. This fixed the issue with GitHub Pages.
- That change then introduced a massive bug as our try_files directives and nginx were configured to expect trailingSlashes endpoints. We quickly worked together to update the nginx config file to properly handle both the new 404s, new $uri schema that implied that a request for (example, /en/about translates to /en/about.html).
- With these new directives we've noticed spikes on file system access that lead us to optimise our directives, enable file caching on nginx and others
- At the meantime we were working against the clock to fix the 404s cache issues by doing numerous experiments on nginx (with cache headers) and CloudFlare cache rules and page rules.
- We've noticed that localised pages that do not exist, were not fallbacking to english, neither the 404s pages were being served in the requested language. This led us to work on these issues...

Rest I think Matt explained.

**Comment by ovflowd** [comment] 2023-03-17 15:51
Continuation for today:

- We kept monitoring on the early morning of the 17th and kept exploring options;
- We identifier another potential point of failure with excessive `try_files` directive, and we decided to remove those directives from static indexed directories such as `/dist`
- We've deployed the fixed for English fallback pages, localized error pages and more
- We identified that `gzip static` directive was causing massive spam of the fs trying to open `.gz` versions of every file request, spamming our system.
- We've deployed CloudFlare firewall rules to block requests from `Artifactory`-based `user-agents` to non-legitimate files (such actually node.js binaries).
- After all these changes, we've noticed a rapid and steady improvement in the health of our systems

**Comment by ovflowd** [comment] 2023-03-17 18:29
Later today:

* We identified a few issues with CF hammering the servers with load-balancing requests and we deployed a new route that should have 0 penalty on our server
* We also discovered that the rule deployed to block spam requests from automated tools such as Artifactory/Gradle was fixed by deploying a fixed ReGeX rule. (Note this issue was a bug on CloudFlare's ReGeX builder).

**Comment by tniessen** [comment] 2023-03-17 19:16
> We identified a few issues with CF hammering the servers with load-balancing requests

Was the request rate just a couple hundred per minute? That would be expected if checks were configured from all colos every 60s. If it was more, it might be indicative of another problem.

**Comment by MattIPv4** [comment] 2023-03-17 19:17
Yeah, it was just the LB checks from every colo, but it was doing disk reads every time because of the route that was being used for it. There's now a route in the NGINX config that returns a 204 directly from NGINX, so those requests aren't causing disk reads.

**Comment by MattIPv4** [comment] 2023-03-22 03:04
I've finished up the main body of the draft above now :)

If folks have any other lessons that should be included here, please shout! Equally if you think any sections should be tweaked etc. please let me know.

The only gap in my understanding of the incident is around the site rebuilding every 5 minutes. I understand that was the issue, and that it was putting more load on the origin, and that it was caused by the migration to Next.js, but what was the fix for it?

**Comment by richardlau** [comment] 2023-03-22 03:05
> The only gap in my understanding of the incident is around the site rebuilding every 5 minutes. I understand that was the issue, and that it was putting more load on the origin, and that it was caused by the migration to Next.js, but what was the fix for it?

https://github.com/nodejs/build/pull/3230

**Comment by MattIPv4** [comment] 2023-03-23 20:07
The postmortem has now been published: https://status.nodejs.org/incidents/svk1f6czgxy6

Thanks again to everyone involved in the incident response, and writing this :)

**Closed** 2023-03-24 02:56 UTC
