### ISSUE TITLE
spurious lint failures in CI

### ISSUE THREAD

**Issue by Trott** [nodejs/build#906] opened 2017-10-08 06:42 UTC
Key line seems to be:

```console
ok 19 - /usr/home/iojs/build/workspace/node-test-lintercat: stdout: Resource temporarily unavailable
```

See https://ci.nodejs.org/job/node-test-linter/12318/console for an example.
 
/cc @refack

**Comment by gibfahn** [comment] 2017-10-08 14:56
Hmm, maybe the machine can't handle that much console logging.

**Comment by gibfahn** [comment] 2017-10-08 14:56
Probably caused by https://github.com/nodejs/build/issues/720#issuecomment-334953619

**Comment by refack** [comment] 2017-10-08 14:59
AFAICT it happened only one (and https://github.com/nodejs/build/issues/720#issuecomment-334953619 is a genius idea!).
RE: "that much console logging" shall I remind you of the 130MB console output for even Windows build ;)

**Comment by refack** [comment] 2017-10-08 15:01
I think there's an stdout race of some sort between `cat` and Jenkins. I just rebuilt that job (https://ci.nodejs.org/job/node-test-linter/12355/console) and got a different truncation:
```
ok 35 - /usr/home/iojs/buBuild step 'Execute shell' marked build as failure
```

**Comment by refack** [comment] 2017-10-08 15:08
Got an incantation - replace `cat` with `grep -v -P "^(ok|1\.\.|TAP|$)" test-eslint.tap", and maybe add an `echo ---------` for good measure.

**Comment by refack** [comment] 2017-10-08 15:27
@Trott to the point of job 12318's failure, see https://github.com/nodejs/node/pull/15805#issuecomment-335013975

**Comment by gibfahn** [comment] 2017-10-08 16:02
Yeah, it's probably due to the speed at which this spewed out 5000 lines of text.

This should be fixed by https://github.com/nodejs/build/issues/720#issuecomment-335012924. I'll close this, reopen if it reoccurs.

**Closed by gibfahn** 2017-10-08 16:02 UTC
