### ISSUE TITLE
nvm being "installed" on jenkins-workspace hosts

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#988] opened 2017-11-08 10:36 UTC
This in .bashrc on test-packetnet-ubuntu1604-x64-1

```
export NVM_DIR="$HOME/build/workspace/node-inspect@tmp/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

Looks like something in the node-inspect job is fully installing nvm. Can we stop that cause it's screwing up bash cause that NVM_DIR isn't stable.

@maclover7 @refack who's is this?

**Comment by rvagg** [comment] 2017-11-08 10:49
I've changed perms on .bashrc and .profile to `444` to prevent this happening again (crossing fingers that nvm isn't _too_ clever)

**Comment by refack** [comment] 2017-11-08 12:58
> who's is this?

Ack, that's me.
That job - https://ci.nodejs.org/job/node-inspect/ - is still in "beta" and hasn't landed yet (ATM only admins should have "run" capa) - https://github.com/nodejs/build/pull/956.

/CC @jkrems

**Comment by refack** [comment] 2017-11-08 13:04
Ping @ljharb is there a way to use `nvm` in a local scope, without it changing global state?

**Comment by jkrems** [comment] 2017-11-08 15:48
Ugh, changed `NVM_HOME` but forgot that its install script is messing with `.bashrc` w/o asking.

@refack It's already installing it in local scope (that's why it's trying to load nvm from the workspace's tmp dir). The problem is that I'm running the install script instead of just git-cloning nvm into the directory myself.

**Comment by jkrems** [comment] 2017-11-08 16:19
Switching to direct git clone which should remove the side effect on bashrc: https://github.com/nodejs/build/pull/956/commits/1fb7b6046ed7304fef291133a6599decb06243c7

**Comment by ljharb** [comment] 2017-11-08 18:30
The primary purposes of the install script is to install nvm and update your profile files; a direct git clone works fine too.

I'm confused tho why simply having those lines in bashrc would be a problem; unless you have a default alias specified, sourcing nvm.sh should be a noop.

**Comment by ljharb** [comment] 2017-11-08 18:30
The primary purposes of the install script is to install nvm and update your profile files; a direct git clone works fine too.

I'm confused tho why simply having those lines in bashrc would be a problem; unless you have a default alias specified, sourcing nvm.sh should be a noop.

**Comment by refack** [comment] 2017-11-08 18:37
The directory defined by `export NVM_DIR="$HOME/build/workspace/node-inspect@tmp/.nvm"` is ephemeral and when it's doesn't exist those statements return exit code 1.

**Comment by ljharb** [comment] 2017-11-08 18:42
They shouldn't; it's in a `test` - both lines are guarded by `-s` checks.

Are you setting some sort of bash options that might make it abnormally exit nonzero?

**Comment by rvagg** [comment] 2017-11-08 22:40
darn, I wish I had have saved the error output because I can't replicate it now by putting it back in. Basically I noticed this when I logged in as root and did `su iojs` to switch to that account and was confronted with 1/2 a screen of error messages, stack traces and whatnot.

so my guess now is that `$HOME/build/workspace/node-inspect@tmp/.nvm` was partly intact so the bash was executing to load it, but something about the node installation wasn't, causing the problem. I'm pretty sure the error I was seeing was Node stack traces, so it was loading Node but not _fully_ somehow?

**Closed** 2017-11-08 22:41 UTC

**Comment by jkrems** [comment] 2017-11-08 22:51
Sorry for the confusion! Should've thought of that. :)

**Comment by refack** [comment] 2017-11-08 22:53
@jkrems I'm trying to learn from this. For example, we should do beta testing only on sandboxed bots.

**Comment by ljharb** [comment] 2017-11-08 23:28
It seems like the issue was that `[ -s "$NVM_DIR/nvm.sh" ]` will not, in fact, fail with `set -e` - but if it's the last line of `.bashrc`, it will cause the process to exit 1.

A simple fix is to make the last line of `.bashrc` exit zero, perhaps by adding `test ||:` or something.
