### ISSUE TITLE
downloads from nodejs.org currently very slow

### ISSUE THREAD

**Issue by kevinburkemeter** [nodejs/build#2210] opened 2020-03-09 01:12 UTC
I have gigabit Fiber internet from Sonic.net. Attempting to download `https://nodejs.org/dist/v12.16.1/node-v12.16.1-linux-x64.tar.gz` - a 20MB file - has currently taken over 6 minutes and counting. It takes a similar amount of time whether I attempt to download from a browser or local.

It is possible I am being rate limited; I have attempted to download that file ten times in the last two hours.

I tried searching for a mirror but the only ones I could find were in China or Europe.

**Comment by kevinburkemeter** [comment] 2020-03-09 01:31
I just tried the same request from a VPN and it's similarly taking at least 6 minutes to download a 20 MB file. So I don't think the issue is limited to my IP address.

**Comment by addaleax** [comment] 2020-03-09 02:00
Fwiw, I just tried to download the file at the above URL and it took 7.9 seconds – maybe this issue has resolved itself in some way?

**Comment by rvagg** [comment] 2020-03-09 04:00
Thanks for reporting it @kevinburkemeter, but unfortunately I can't find any record of any issues on our end.

Cloudflare isn't reporting that they've had any significant problems: https://www.cloudflarestatus.com/

DigitalOcean, where the majority of our Cloudflare traffic is pulled from isn't either: https://status.digitalocean.com/

And the primary droplet that would have served the binary if it wasn't available at the Cloudflare edge locations that you were talking to is also looking pretty stable:

<img width="795" alt="Screenshot 2020-03-09 14 58 12" src="https://user-images.githubusercontent.com/495647/76181837-aed1a980-6216-11ea-87c2-2d64ae768409.png">

I'm going to close this issue as "unable to replicate" but would be interested to hear if it continues or if anyone else experiences similar problems.

**Closed by rvagg** 2020-03-09 04:00 UTC

**Comment by kevinburkemeter** [comment] 2020-03-09 04:27
OK, appreciate you looking, I'll try to post more info if I experience it again. Just covering the bases:

- plenty of disk space on the client
- nothing CPU intensive running on the client
- nothing bandwidth intensive running on the client
- ISP does not rate limit

**Comment by jgehrcke** [comment] 2020-04-06 13:41
In our CI we had download failures yesterday and also today the downloads are extremely slow.

**Comment by rvagg** [comment] 2020-04-07 04:57
dupe of #2263
