### ISSUE TITLE
macos11.0 release hosts are both offline

### ISSUE THREAD

**Issue by targos** [nodejs/build#3179] opened 2023-02-05 14:54 UTC
[release-nearform-macos11.0-arm64-1](https://ci-release.nodejs.org/manage/computer/release-nearform-macos11.0-arm64-1/) is offline and its IP address is unreachable
[release-macstadium-macos11.0-arm64-1](https://ci-release.nodejs.org/manage/computer/release-macstadium-macos11.0-arm64-1/) is offline and [refuses ssh connections](https://github.com/nodejs/build/issues/3084)

**Comment by richardlau** [comment] 2023-02-06 17:26
I've sent an email to our NearForm contacts regarding the NearForm machine. (FYI @efrisby).

**Comment by mhdawson** [comment] 2023-02-06 21:27
@UlisesGascon is 

> [release-macstadium-macos11.0-arm64-1](https://ci-release.nodejs.org/manage/computer/release-macstadium-macos11.0-arm64-1/) is offline and https://github.com/nodejs/build/issues/3084

Something you can help with?

**Comment by UlisesGascon** [comment] 2023-02-07 07:02
I can help and see if I can restore the machine, but I will need some support to re-ansible as we did for `release-orka-10.15-x64-1` in [the past](https://github.com/nodejs/build/issues/3112#issuecomment-1370776065)

**Comment by targos** [comment] 2023-02-07 07:10
Before re-ansibling, maybe there is a secondary way to access the machine from Macstadium's infra/network?

**Comment by UlisesGascon** [comment] 2023-02-07 07:35
I will check the machine and share the status before I do a destructive or non-reversible action 👍

**Comment by UlisesGascon** [comment] 2023-02-07 13:24
Here is an update on what I have tried. Thanks to @targos for the great support:

- I reviewed the internal documents about MacStadium but did not find a new way to access the machines.
- The MacStadium web UI does not offer any option to access the machine, but the stats confirmed that they are connected and running. 
- I hard rebooted all the bare metal machines (including the test ones,  #3084), but even after the machines were back online, none of them had improved connectivity. 
- I tried to VNC connect with them following an [official tutorial (from 10 years ago)](https://www.youtube.com/watch?v=OVQHK-0-GJw) but had no luck, possibly because the username and password were not the same as in the internal documentation or the VNC Server is disabled (as expected).
- I also reviewed the Bare Metal official documentation but had no luck. 
- I attempted to communicate to the machines from the Orka VPN but was unsuccessful.

I see two options: we can raise a ticket and ask for support, pointing to this issue, or we can add one or several additional release VMs in the Orka platform using [the backups I made](https://github.com/nodejs/build/issues/3112#issuecomment-1378632482). We would only need to register the new machines in the inventory and re-Ansible them.

**Comment by richardlau** [comment] 2023-02-07 13:31
> I see two options: we can raise a ticket and ask for support

Am I misremembering or did @AshCripps try that before (or perhaps it was a different VM)?

**Comment by UlisesGascon** [comment] 2023-02-07 17:10
In the meantime I will add a new macos11 in Orka for releases

**Comment by AshCripps** [comment] 2023-02-07 17:59
> > I see two options: we can raise a ticket and ask for support
> 
> Am I misremembering or did @AshCripps try that before (or perhaps it was a different VM)?

Yes it was a very similar issue and took some effort to get them to acknowledge it - should still be in the system somewhere of what I asked for.

**Comment by richardlau** [comment] 2023-02-07 18:08
> In the meantime I will add a new macos11 in Orka for releases

Ah, forgot that these are arm64 machines/VMs and therefore not in Orka.

**Comment by UlisesGascon** [comment] 2023-02-07 21:46
🎉 Good News! I created a new bare metal instance, and the machine is up and running. 

So... here is **the plan**:
- [ ] I will create a PR to replace the IP for `release-macstadium-macos11.0-arm64-1` in the inventory, and I will ask you to reansible the machine for releases and to include it in the secret repo.
- [ ] I will create 2 new machines, reansible them to replace the test-macstadium-*-arm64-*
- [ ] Once we are happy with the new machines I will remove the old ones from macstadium

**Comment by richardlau** [comment] 2023-02-08 14:51
FWIW the Nearform machine is now back online. (Thank you @efrisby.)

**Comment by richardlau** [comment] 2023-02-09 13:28
I've reansibled the release and two test macos11 arm64 macstadium machines.
Currently running a release rebuild on today's nightly (osx11-tar happened to fail) with just osx11-tar and osx11-pkg: https://ci-release.nodejs.org/job/iojs+release/9138/

**Comment by richardlau** [comment] 2023-02-09 14:13
> Currently running a release rebuild on today's nightly (osx11-tar happened to fail) with just osx11-tar and osx11-pkg: https://ci-release.nodejs.org/job/iojs+release/9138/

Build passed. Release machine looks good.

**Comment by UlisesGascon** [comment] 2023-02-10 17:51
Thanks for the conformation @richardlau. I will close the issue then 😉

**Closed by UlisesGascon** 2023-02-10 17:51 UTC
Labels: platform:osx, incident, ci-release
