### ISSUE TITLE
test-osuosl-aix61-ppc64_be-2  test failures

### ISSUE THREAD

**Issue by Trott** [nodejs/build#984] opened 2017-11-07 16:46 UTC
I took test-osuosl-aix61-ppc64_be-2 offline because it running node-test-commit-aix was a sea of red with failures on parallel/test-repl-envvars. I *think* this is a build thing and not a test issue. Anyone have any better information on that, though?

/cc @gireeshpunathil @refack @mhdawson 

Refs: https://github.com/nodejs/node/issues/16859

**Comment by mhdawson** [comment] 2017-11-07 16:58
@gireeshpunathil once you figure out what is going on please get either @refack or @gibfahn to help make the change on the machine that was disabled/reenable.

**Comment by refack** [comment] 2017-11-07 23:11
That server I bonkers.
1) It's failing with a perfectly good test (`parallel/test-repl-envvars` passes as is on `test-osuosl-aix61-ppc64_be-1`
2) gives compilation errors (https://ci.nodejs.org/job/node-test-commit-aix/10098/nodes=aix61-ppc64/console)
Please don't bring on-line until it's fixed

**Comment by refack** [comment] 2017-11-07 23:11
P.S. I even rebooted, and it didn't help.

**Comment by mhdawson** [comment] 2017-11-08 00:05
@refack I've been told its not really expected that AIX machines are rebooted often like you would with linux machines. It is the recommendation of our AIX contact that we only do it when absolutely necessary...  Likely not an issue but just to ask that we don't do it too often.

**Comment by mhdawson** [comment] 2017-11-08 00:13
One, other thing to consider is if the rest of the tests pass, and its going to take a while to figure out what the issue is with this specific test, one option is to exclude the test.  Even though we have the other machine we should keep an eye on whether we end up with a big backlog because we are down to a single machine.

**Comment by mhdawson** [comment] 2017-11-08 00:29
@gibfahn I think @gireeshpunathil may already have access to the AIX machines but if not can you facilitate that.

**Comment by mhdawson** [comment] 2017-11-08 01:30
Seems to have failed in CI. Going to kill and restart the jenkins agent in case it is related to how it was started

**Comment by mhdawson** [comment] 2017-11-08 02:03
Passed in this run: https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix61-ppc64/10103/console.

My only guess may be that it might somehow be related to how the jenkins agent is started.

What I used was (and have used in the past):
```
sh /etc/rc.d/rc2.d/S20Jenkins started as the root user from a bash shell
```
I wonder if there is something subtly different when it gets started automatically on reboot.

**Comment by mhdawson** [comment] 2017-11-08 02:07
Going to leave enabled.  The only difference between the passing and previous failing run was me killing and restarting the agent so I'm hoping that is what caused the passing run and means the jobs will continue to pass on the machine as well.

**Comment by refack** [comment] 2017-11-08 12:29
https://ci.nodejs.org/computer/test-osuosl-aix61-ppc64_be-2/builds
Looking good 👍 
![image](https://user-images.githubusercontent.com/96947/32549186-8205978c-c456-11e7-90a7-19bcf64f854e.png)

**Comment by refack** [comment] 2017-11-08 12:31
Closing as this seems resolved.

#### Summary:
* Restarting the Jenkins agent can solve ghosts
* Should avoid rebooting AIX hosts

**Closed by refack** 2017-11-08 12:31 UTC
Labels: incident, infra, jenkins-ci
