### ISSUE TITLE
Give @shigeki access to linuxOne machine for openSSL work

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1246] opened 2018-04-20 16:57 UTC
See: https://github.com/nodejs/node/issues/19944#issuecomment-382943583
 
@shigeki is a long standing Node.js collaborator and past TSC member

**Comment by mhdawson** [comment] 2018-04-20 16:58
+1
@nodejs/build

**Comment by Trott** [comment] 2018-04-20 17:36
+1

**Comment by gibfahn** [comment] 2018-04-22 17:34
+1

**Comment by shigeki** [comment] 2018-04-23 19:31
If it allowed, I'd like to have an access it in order to check if OpenSSL-1.1.0 built with Node is properly by comparing those built from the OpenSSL sources.  I also need to submit a patch for S390 of https://github.com/nodejs/node/commit/1bcb6c0d26de749a806523de97b9309da839514d to the upstream but I never checked it on that machine except CI jobs of Node.
https://github.com/shigeki.keys are my public keys.

**Comment by Trott** [comment] 2018-04-23 22:27
Aside: Looks like we may need to update the ansible stuff so that the ssh config writing playbook writes info for `test-linuxonecc-rhel72-s390x-3`? I'm only getting `-1` and `-2`.

**Comment by Trott** [comment] 2018-04-23 22:30
@shigeki I've added your public keys to test-linuxonecc-rhel72-s390x-2. Let me know if the work you're doing requires us to take it out of the CI rotation. When you're done, leave a comment here and I'll remove your keys (or remove them yourself) and close this issue.

**Comment by shigeki** [comment] 2018-04-24 05:43
@Trott Thanks. I can login the machine and make test builds of openssl and node in `/data/shigeki`. Build binaries were already transferred to my local machine but they are not yet checked. And checking my openssl PR is not yet done, too. Please keep my access for a while. I will ask you to remove my access after my all tasks finished. Thanks, again.

**Comment by mhdawson** [comment] 2018-04-24 15:01
@Trott good point on -3, I added those as one to test the new compiler changes, I'll figure out if I'm going to remove from the CI or add to ansible.

**Comment by gdams** [comment] 2018-05-30 18:12
@shigeki is your access still required here?

**Comment by maclover7** [comment] 2018-06-03 14:43
Removed access from `test-linuxonecc-rhel72-s390x-2`, easy enough to add back later if still needed

**Closed by maclover7** 2018-06-03 14:43 UTC
Labels: access request

**Comment by shigeki** [comment] 2018-06-03 14:51
Thanks. I've confirmed that it's no problem.
