### ISSUE TITLE
node-test-commit-linuxone doesn't post status to PR when triggered directly

### ISSUE THREAD

**Issue by refack** [nodejs/build#768] opened 2017-06-22 14:12 UTC
https://ci.nodejs.org/job/node-test-commit-linuxone/build?delay=0sec
![image](https://user-images.githubusercontent.com/96947/27438337-e489c770-5732-11e7-8b23-07f3c415e5c5.png)
others (e.g. `node-test-linter`)
![image](https://user-images.githubusercontent.com/96947/27438358-f741534c-5732-11e7-8802-3a5bde7a0459.png)

Entering the ID doesn't work, but when triggered by `node-test-commit` it does post it's status to the PR

**Comment by gibfahn** [comment] 2017-06-22 22:36
Looks like the `linuxone` parameter was wrongly configured. `node-test-commit` passes down `$POST_STATUS_TO_PR` (and that's what the linuxone script checks), but `node-test-commit-linuxone` was setting `$POST_TO_PR_ID` instead.

Should be fixed now.

**Comment by refack** [comment] 2017-06-23 22:49
I see the name change, but type is still "text"
![image](https://user-images.githubusercontent.com/96947/27502792-b0dfcc68-5844-11e7-96e9-9f2d54e88448.png)

**Comment by refack** [comment] 2017-06-23 22:54
Just has an idea to pass `true` as a string and that works.
![image](https://user-images.githubusercontent.com/96947/27502879-5df48196-5845-11e7-98bd-d787c6e75658.png)

**Comment by gibfahn** [comment] 2017-06-23 23:31
>I see the name change, but type is still "text"

Oh yeah, I didn't think about that. In Jenkins parameters are just environment variables, so boolean params are just the string `true` or `false`. I've fixed that now.

**Comment by refack** [comment] 2017-06-23 23:50
Wonderful

**Comment by maclover7** [comment] 2017-11-07 23:21
Confirmed this is fixed, going to close out.

**Closed by maclover7** 2017-11-07 23:21 UTC
