### ISSUE TITLE
flakes in node-test-commit-v8-linux/nodes=benchmark

### ISSUE THREAD

**Issue by refack** [nodejs/build#936] opened 2017-10-23 10:51 UTC
Refs: https://github.com/nodejs/node/issues/16398
[1005](https://ci.nodejs.org/job/node-test-commit-v8-linux/1005/) failed
[1006](https://ci.nodejs.org/job/node-test-commit-v8-linux/1006/) passed
[1007](https://ci.nodejs.org/job/node-test-commit-v8-linux/1007/) passed
[1008](https://ci.nodejs.org/job/node-test-commit-v8-linux/1008/) failed
[1009](https://ci.nodejs.org/job/node-test-commit-v8-linux/1009/) failed
[1010](https://ci.nodejs.org/job/node-test-commit-v8-linux/1010/) pass
[1011](https://ci.nodejs.org/job/node-test-commit-v8-linux/1011/) pass (similar to 1005)
(there no apparent correlation with source changes)

The fail is when `v8/deps/test/message/console.js` compares actual vs expected output to `stdout` and `stderr`:

Actual output:
```default: 30.762000
abcd: 0.055000
b: 0.000000
a: 0.001000
log more
warn 2
debug
info
/home/iojs/build/workspace/node-test-commit-v8-linux/nodes/benchmark/v8test/v8test/deps/v8/test/message/console.js:25: Error: exception
console.info({ toString: () => {throw new Error("exception");} })
                                ^
Error: exception
    at Object.toString (/home/iojs/build/workspace/node-test-commit-v8-linux/nodes/benchmark/v8test/v8test/deps/v8/test/message/console.js:25:39)
    at console.info (<anonymous>)
    at /home/iojs/build/workspace/node-test-commit-v8-linux/nodes/benchmark/v8test/v8test/deps/v8/test/message/console.js:25:9
```

Expected output:

```default: {NUMBER}
abcd: {NUMBER}
b: 0.000000
a: {NUMBER}
log more
warn 2
debug
info
*%(basename)s:25: Error: exception
console.info({ toString: () => {throw new Error("exception");} })
                                ^
Error: exception
    at Object.toString (*%(basename)s:25:39)
    at console.info (<anonymous>)
    at *%(basename)s:25:9
```

**Comment by fhinkel** [comment] 2017-10-23 11:03
Thanks for opening in the right repo.

**Comment by rvagg** [comment] 2017-10-31 04:11
Can't explain this one, but since some of the weirdest infra problems have been solved with a reboot I've done that! Updated the machine while I was at it, I'm not sure it'd been updated since first installed (I hope I haven't messed up the benchmarks in the process!).

Re-ran last job and it looks OK for now, let's keep an eye on it and see if the problem returns.

https://ci.nodejs.org/job/node-test-commit-v8-linux/1026/nodes=benchmark,v8test=v8test/

**Comment by refack** [comment] 2017-10-31 18:28
It's still there https://ci.nodejs.org/job/node-test-commit-v8-linux/nodes=benchmark,v8test=v8test/1027/console

**Comment by rvagg** [comment] 2017-11-01 02:34
OK, I've got build 1027's state copied and compiled and I can repeat the failure. I don't have time to figure it out but I have it sitting in a directory on that server that won't be deleted (automatically), so who wants to take a look? @nodejs/v8

```
iojs@nodejsb1:~/v8test_temp_gh_build_936$ /home/iojs/v8test_temp_gh_build_936/deps/v8/out/x64.release/d8 --test --random-seed=1505382534 --no-stress-opt --nohard-abort /home/iojs/v8test_temp_gh_build_936/deps/v8/test/message/console.js
default: 0.001000
abcd: 0.027000
b: 0.000000
a: 0.001000
log more
warn 2
error
debug
info
/home/iojs/v8test_temp_gh_build_936/deps/v8/test/message/console.js:25: Error: exception
console.info({ toString: () => {throw new Error("exception");} })
                                ^
Error: exception
    at Object.toString (/home/iojs/v8test_temp_gh_build_936/deps/v8/test/message/console.js:25:39)
    at console.info (<anonymous>)
    at /home/iojs/v8test_temp_gh_build_936/deps/v8/test/message/console.js:25:9
```

**Comment by rvagg** [comment] 2017-11-01 03:01
More:

```
iojs@nodejsb1:~/v8test_temp_gh_build_936$ echo $?
0
```

:shrug: someone should take a look though and see if you can make sense why this is failing in CI

**Comment by fhinkel** [comment] 2017-11-01 17:03
Thanks @rvagg . Do you get consistent failure with the copy of 1027? Or is it flaky?

**Comment by rvagg** [comment] 2017-11-01 22:18
@fhinkel well, I get consistent output that I pasted above, but exit status for the test is `0` to maybe that's not actually a failure?

**Comment by rvagg** [comment] 2017-11-01 22:25
@fhinkel I've put your github keys onto that machine, `ssh iojs@50.23.85.254` and look in the `v8test_temp_gh_build_936` directory for that clone of 1027. You can run `/home/iojs/v8test_temp_gh_build_936/deps/v8/out/x64.release/d8 --test --random-seed=1505382534 --no-stress-opt --nohard-abort /home/iojs/v8test_temp_gh_build_936/deps/v8/test/message/console.js` to replicate the failing bit.

**Comment by fhinkel** [comment] 2017-11-02 09:07
Thanks! Investigating. Will let you know when you can delete my keys again.

**Comment by fhinkel** [comment] 2017-11-02 09:36
That build doesn't reproduce the error for me. Message tests are somewhat confusing:  The message tests are supposed to throw error messages. The test runner compares the output with the `*.out` files. So running just the test file with `d8` looks like an error, but the test actually passes because the output matches the expected output.  

```
iojs@nodejsb1:~/v8test_temp_gh_build_936$ ./deps/v8/tools/run-tests.py --arch=x64 --mode=release message/console
>>> Running tests for x64.release
No connection to distribution server; running tests locally.
[00:00|% 100|+   1|-   0]: Done   
```

Pinging @hashseed as he has touched the test case in the past if he has any idea why this might be flaky on the CI. When the test on the CI fails, the output looks to my eye exactly like the expected output :confused:

**Comment by hashseed** [comment] 2017-11-02 10:11
Doesn't ring a bell. I have never seen this test fail before, and the expectation file seems to match the output too.

**Comment by fhinkel** [comment] 2017-11-03 13:24
@georgneis figured it out :fireworks: There's a regex checking that the time is a number - with 1 decimal in front of the period. So anything longer than 10 milliseconds fails the regex check. We'll fix this on the V8 side.

**Comment by fhinkel** [comment] 2017-11-03 13:25
I guess we can close this?

**Closed by fhinkel** 2017-11-03 13:25 UTC
Labels: bug, incident, jenkins-ci

**Comment by rvagg** [comment] 2017-11-04 00:40
phew! what a relief, thanks @fhinkel & @GeorgNeis. I'll remove those keys from the server now.
