### ISSUE TITLE
Update GCC on  benchmark-ubuntu1604-intel-64

### ISSUE THREAD

**Issue by targos** [nodejs/build#2681] opened 2021-06-22 06:30 UTC
See https://ci.nodejs.org/job/node-test-commit-v8-linux/4078/nodes=benchmark-ubuntu1604-intel-64,v8test=v8test/console

Since we increased our minimum supported GCC version to >=8.3, V8 already removed hacks that they had to support old versions. Now V8 CI fails on the benchmark machine because GCC is too old:

```
15:19:43 + ./configure --verbose
15:19:45 Node.js configure: Found Python 3.9.4...
15:19:45 Detected C++ compiler (CXX=g++-6) version: 6.5.0
15:19:45 WARNING: C++ compiler (CXX=g++-6, 6.5.0) too old, need g++ 8.3.0 or clang++ 8.0.0
15:19:45 Detected C compiler (CC=gcc-6) version: 6.5.0
```

```
15:41:19 ../deps/v8/src/compiler/node.h:53:29: error: enclosing class of constexpr non-static member function ‘v8::internal::compiler::IrOpcode::Value v8::internal::compiler::Node::opcode() const’ is not a literal type
15:41:19    constexpr IrOpcode::Value opcode() const {
15:41:19                              ^~~~~~
15:41:19 ../deps/v8/src/compiler/node.h:42:7: note: ‘v8::internal::compiler::Node’ is not literal because:
15:41:19  class V8_EXPORT_PRIVATE Node final {
15:41:19        ^~~~
15:41:19 ../deps/v8/src/compiler/node.h:42:7: note:   ‘v8::internal::compiler::Node’ is not an aggregate, does not have a trivial default constructor, and has no constexpr constructor that is not a copy or move constructor
```

**Comment by rvagg** [comment] 2021-06-22 07:11
Perhaps a duplicate of #2656, it really just needs an upgrade. /cc @aduh95

We can do this, but need to find a time slot when it won't matter if we screw it up and have to scramble to get nearForm to help us revive it.

**Comment by richardlau** [comment] 2021-06-22 16:44
I agree that we need to look at updating the benchmark machines to Ubuntu 20.04. 

In the meantime our Ansible scripts do install gcc/g++ 8 on Ubuntu 16.04 https://github.com/nodejs/build/blob/3aaa7232294686ceb184942616696bb2ad0a1992/ansible/roles/baselayout/vars/main.yml#L155-L157 but it's been a while since we ran the scripts on the benchmarking machines (but we have done so in the past (https://github.com/nodejs/build/pull/1975#issuecomment-545237763)).

I've updated the Ansible scripts in https://github.com/nodejs/build/pull/2682 so we can run the Jenkins worker create playbook in `--check` mode (i.e. show what changes Ansible thinks it would make without making them) and after reviewing felt that it looked safe enough to run the playbook without `--check` (i.e. make the change). So both nearform benchmark machines now have `gcc-8` available and https://github.com/nodejs/build/pull/2684 will select it for Node.js 16 and later (the V8 CI already uses the `select-compiler.sh` script).

**Comment by richardlau** [comment] 2021-06-23 10:36
As shown (missed by me) in the snippet from the Ansible script in my previous comment I'd previously missed updating the copy/pasted `g++-8` (so instead had a duplicate `g++-6`) for Ubuntu 16.04. Fixing now with https://github.com/nodejs/build/pull/2686.

**Closed** 2021-06-23 10:46 UTC
