### ISSUE TITLE
Node.js  Build WorkGroup Meeting 2021-03-16

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#2562] opened 2021-03-10 13:05 UTC
## Time

**UTC Tue 16-Mar-2021 21:00 (09:00 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Tue 16-Mar-2021 14:00 (02:00 PM) |
| US / Mountain | Tue 16-Mar-2021 15:00 (03:00 PM) |
| US / Central  | Tue 16-Mar-2021 16:00 (04:00 PM) |
| US / Eastern  | Tue 16-Mar-2021 17:00 (05:00 PM) |
| EU / Western  | Tue 16-Mar-2021 21:00 (09:00 PM) |
| EU / Central  | Tue 16-Mar-2021 22:00 (10:00 PM) |
| EU / Eastern  | Tue 16-Mar-2021 23:00 (11:00 PM) |
| Moscow        | Tue 16-Mar-2021 24:00 (12:00 AM) |
| Chennai       | Wed 17-Mar-2021 02:30 (02:30 AM) |
| Hangzhou      | Wed 17-Mar-2021 05:00 (05:00 AM) |
| Tokyo         | Wed 17-Mar-2021 06:00 (06:00 AM) |
| Sydney        | Wed 17-Mar-2021 08:00 (08:00 AM) |

Or in your local time:
* https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Build%20WorkGroup+Meeting+2021-03-16&iso=20210316T2000
* or https://www.wolframalpha.com/input/?i=08PM+UTC%2C+Mar+16%2C+2021+in+local+time

## Links

* Minutes Google Doc: <https://docs.google.com/document/d/1CFZAhH9GHidHbLa6g5S9oA83ggCU52VGYfMbvKUxJt4/edit>

## Agenda

Extracted from **build-agenda** labelled issues and pull requests from the **nodejs org** prior to the meeting.

### nodejs/build

* Interest in establishing a "Build Helper" role [#2550](https://github.com/nodejs/build/issues/2550)
* Apple silicon builds [#2474](https://github.com/nodejs/build/issues/2474)
* Install Python 3 everywhere in CI [#2507](https://github.com/nodejs/build/issues/2507)
* Remove explicit setting of PYTHON in CI jobs [#2576](https://github.com/nodejs/build/issues/2576)

## Invited

* Build team: @nodejs/build

## Notes

The agenda comes from issues labelled with `build-agenda` across **all of the repositories in the nodejs org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

* link for participants: https://zoom.us/j/715960833
* For those who just want to watch: We stream our conference call straight to YouTube so anyone can listen to it live, it should start playing at https://www.youtube.com/c/nodejs+foundation/live when we turn it on. There's usually a short cat-herding time at the start of the meeting and then occasionally we have some quick private business to attend to before we can start recording & streaming. So be patient and it should show up.
* youtube admin page: https://www.youtube.com/my_live_events?filter=scheduled

**Comment by AshCripps** [comment] 2021-03-15 13:34
I did ask Michael to move this back to original time but forgot about north america changing the clocks earlier than us - would moving it an hour later make it easier for you to attend @rvagg?

**Comment by rvagg** [comment] 2021-03-16 05:18
yes, an hour later is a bit easier for me (if I remember and if that time is still accurate given the DST shifts currently occurring!)

**Comment by AshCripps** [comment] 2021-03-16 09:57
In that case is everyone else happy with moving the meeting an hour later today? @nodejs/build

**Comment by richardlau** [comment] 2021-03-16 10:25
> In that case is everyone else happy with moving the meeting an hour later today? @nodejs/build

I'm fine either way.

**Comment by richardlau** [comment] 2021-03-16 17:40
I can give an update on the status of 
* Install Python 3 everywhere in CI [#2507](https://github.com/nodejs/build/issues/2507)
* Remove explicit setting of PYTHON in CI jobs [#2576](https://github.com/nodejs/build/issues/2576)

**Comment by jbergstroem** [comment] 2021-03-16 18:33
To be clear: the time in the issue is the updated time?

**Comment by mhdawson** [comment] 2021-03-16 18:38
hour later works for me.

**Comment by mhdawson** [comment] 2021-03-16 18:38
@jbergstroem I don't think the issue is updated. My understand is that we are moving to 5 ET.

**Comment by AshCripps** [comment] 2021-03-16 19:05
Yep 5ET ill update the table now

**Comment by jbergstroem** [comment] 2021-03-16 19:14
Ok, I will have to pass then - I have a conflict. From my end:
- work tangential to #1827 , #2568 
- reviewing grafana output to correlate with our issues with `www` timing out
- (upcoming) pass on knowledge related to backup/metrics machines to @AshCripps

**Comment by rvagg** [comment] 2021-03-16 21:05
@jbergstroem for future reference, is the earlier slot going to be more likely possible for you than this later one?

**Closed** 2021-03-22 14:11 UTC
