### ISSUE TITLE
Minor inconsistency in tarball name vs untarred name for 32 bit package

### ISSUE THREAD

**Issue by springmeyer** [nodejs/build#45] opened 2015-02-11 02:28 UTC
I noticed that `https://iojs.org/download/release/v1.1.0/iojs-v1.1.0-linux-x86.tar.gz` unpacks as `/iojs-v1.1.0-linux-ia32` instead of `iojs-v1.1.0-linux-x86`. Ideally this would be consistent with node which uses `x86` for the directory inside the tarball.

**Comment by rmg** [comment] 2015-02-16 18:40
I took a quick (as in 15 minutes of `git grep` and head scratching) look at the build scripts and couldn't see any places in iojs itself where the tarball name isn't derived from the directory name.

@rvagg could this is happening in an upload script?

**Comment by rvagg** [comment] 2015-02-16 21:48
yes, it's done at upload time to keep the names consistent in /dist/:

```
farch=$ARCH
[[ $farch == 'ia32' ]] && farch='x86'
ssh iojs-www "mkdir -p staging/release/${version}"
scp -p iojs-${version}-linux-${ARCH}.tar.gz iojs-www:staging/release/${version}/iojs-${version}-linux-${farch}.tar.gz
scp -p iojs-${version}-linux-${ARCH}.tar.xz iojs-www:staging/release/${version}/iojs-${version}-linux-${farch}.tar.xz
ssh iojs-www "touch staging/release/${version}/iojs-${version}-linux-${farch}.tar.gz.done staging/release/${version}/iojs-${version}-linux-${farch}.tar.xz.done"
```

prior to this the build is done with:

```
make -j$JOBS binary DESTCPU=$DESTCPU ARCH=$ARCH
```

it's `ARCH` that needs changing on those machines

**Comment by jbergstroem** [comment] 2015-11-26 12:48
Not a bug. @rvagg?

**Comment by rvagg** [comment] 2015-11-30 11:11
was a bug, fixed now afaik

**Closed by rvagg** 2015-11-30 11:11 UTC
Labels: bug, build
