### ISSUE TITLE
rsync endpoint to mirror the releases

### ISSUE THREAD

**Issue by davglass** [nodejs/build#55] opened 2015-02-20 17:48 UTC
Any thought on adding an rsync endpoint for this:

https://iojs.org/download/release/

**Comment by mikeal** [comment] 2015-02-20 17:51
+1

**Comment by bengl** [comment] 2015-12-15 00:20
+1! (but for http://nodejs.org/dist)

**Comment by rvagg** [comment] 2015-12-15 00:50
/dist is an alias for /download/release now fwiw

**Comment by fhemberger** [comment] 2016-04-22 05:04
Can we please add the rsync endpoint for /dist?
https://github.com/nodejs/nodejs.org/issues/662#issuecomment-211986085

**Comment by jbergstroem** [comment] 2016-04-22 23:47
I can look at doing this if others in the build group agree.

**Comment by rvagg** [comment] 2016-05-31 09:22
So I had a thought (:boom:): one of the blockers we have here is hesitation about exposing an unencrypted endpoint while we're trying to move everything to TLS (http://nodejs.org will be fully redirected soon). So, how about we be upfront about this and stand up a host named `insecure.nodejs.org` and expose stuff via http, rsync and even maybe ftp (does anyone still use ftp?). The name points to our opinions re security, you opt in to the risk by putting "insecure" in your scripts. We can isolate it by having the primary server push updates to it so the new host doesn't have any special access to anything. When we go fully `https` for nodejs.org, having an `http` fallback host if people absolutely need it might be a nice touch.

**Comment by jbergstroem** [comment] 2016-05-31 10:07
@rvagg I like it. How about adding a http header about expiration as well; putting a final nail in the coffin to plaintext stuff? `X-Service-Will-Expire: 2020-01-01` (or the rsync equivalent in message)

**Comment by jbergstroem** [comment] 2016-05-31 13:29
(as well as serving the same message with /index.html)

**Comment by mhdawson** [comment] 2016-05-31 14:27
Would unencrypted.nodejs.org work ?  Not to bikeshed but insecure implies a lot more to me than just not protected by encryption which I think would be the main difference.

**Comment by jbergstroem** [comment] 2016-06-29 04:23
Just a quick update: We have an endpoint set up for testing; pm me on irc (jbergstroem) or shoot me an email (bugs at bergstroem dot nu) if you want to give it a whim. If everything works as intended we'll make this public shortly.

**Comment by rvagg** [comment] 2016-06-29 05:04
@jbergstroem do we have it syncing in cron yet? last I checked that wasn't enabled.

**Comment by jbergstroem** [comment] 2016-06-29 14:21
@rvagg nope, still todo. Also, adding it to the deploy script for 0day.

**Comment by jbergstroem** [comment] 2016-07-18 23:38
We're nearly there. I've gotten som feedback and based on that I'd like to suggest extending our EOL/reconsider to 2022 (+2y). I'll land the sync script we'll run from both deploy and cronjob this week.

**Comment by jsumners** [comment] 2017-01-03 20:08
I've been noticing an issue where the release files will sometimes not be available. For example, `rsync://unencrypted.nodejs.org/nodejs/release/v6.9.2/` may have the `docs` directory but nothing else. This definitely causes a problem when the `--delete` option is passed to rsync.

**Comment by jbergstroem** [comment] 2017-01-03 20:38
@jsumners the rsync routine isn't fully up to par. Apologies about that. When we moved web servers a few things changed which made it break. It will obviously work pristine once deemed 'production' worthy, but that doesn't mean we shouldn't fit it as soon as possible. I'll have a look in within a day or so; just got mixed up amongst my other todo's.

**Comment by jbergstroem** [comment] 2017-01-03 21:01
@jsumners hey; I've redeployed it now. It should be populating and be up to speed pretty soon; updating dns as we speak. If you could verify that things look better in the hour or so, that'd be cool!

**Comment by jsumners** [comment] 2017-01-03 21:45
@jbergstroem permissions are broken:

```
[jsumners@node] ~/ $ rsync rsync://unencrypted.nodejs.org/nodejs/
drwxrwxr-x           8 2016/11/17 13:02:06 .
drwxr-xr-x          46 2017/01/03 05:10:02 chakracore-nightly
drwxr-xr-x           2 2015/08/30 04:29:25 next-nightly
drwxr-xr-x         492 2017/01/03 13:05:02 nightly
drwx------           2 2017/01/03 16:05:29 rc
drwx------           2 2017/01/03 16:05:29 release
drwx------           2 2017/01/03 16:05:29 test
```

**Comment by jbergstroem** [comment] 2017-01-03 21:54
@jsumners that's because rsync hasn't finished processing those folders just yet. Thanks for checking!

**Comment by jbergstroem** [comment] 2017-01-03 22:34
Looks like it's done:
```
NEXT                         LEFT       LAST                         PASSED       UNIT                         ACTIVATES
Tue 2017-01-03 22:45:00 UTC  10min left Tue 2017-01-03 22:30:01 UTC  4min 20s ago rsyncmirror.timer            rsyncmirror.service
```

**Comment by jsumners** [comment] 2017-01-03 22:48
@jbergstroem looking good over here. I'll keep an eye on it.

**Comment by ofrobots** [comment] 2017-05-30 19:55
Would it be possible to allow a rsync over ssh?

**Comment by jbergstroem** [comment] 2017-05-30 19:56
@ofrobots that means we'd have to figure out some kind of ssh jail, right?

**Comment by ofrobots** [comment] 2017-05-30 19:57
Yup. Has this been considered? I haven't seen this discussed anywhere.

**Comment by jbergstroem** [comment] 2017-05-30 21:07
@ofrobots http://nginx.org/en/docs/http/ngx_http_autoindex_module.html

**Comment by gibfahn** [comment] 2017-05-30 21:09
Using https://nodejs.org/dist/index.json was suggested in the meeting, @ofrobots let us know whether that works for you.

**Comment by jbergstroem** [comment] 2017-05-30 21:10
[slight hijack here] According to documentation, autoindex is compiled in by default, so I'll see what we can do here.

**Comment by jsumners** [comment] 2017-11-02 13:58
The latest release currently available on the rsync server is v8.6.0. It looks like it isn't being updated again.

**Comment by joaocgreis** [comment] 2017-11-03 17:09
The timer that synchronizes the server was not enabled by default, and was disabled by a reboot. Should be fixed now.

**Comment by jsumners** [comment] 2017-11-03 17:18
👍

**Comment by AndersTrier** [comment] 2018-08-17 13:14
I pulled a copy to mirrors.dotsrc.org which is hosted at Aalborg University, Denmark:
http://mirrors.dotsrc.org/nodejs
https://mirrors.dotsrc.org/nodejs
ftp://mirrors.dotsrc.org/nodejs
rsync://mirrors.dotsrc.org/nodejs

Fell free to send some traffic our way. We sync every 6 hours.

@ofrobots @jbergstroem 
If you want to tunnel rsync over ssh, have a look at the rrsync restricted shell:
https://www.samba.org/ftp/unpacked/rsync/support/rrsync
https://www.guyrutenberg.com/2014/01/14/restricting-ssh-access-to-rsync/

**Comment by sam-github** [comment] 2020-01-28 17:11
Closing as stale, but if anyone wants to take this up feel free to reopen.

**Closed by sam-github** 2020-01-28 17:11 UTC
Labels: enhancement, infra
