### ISSUE TITLE
Test npm on the CI

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/build#234] opened 2015-11-02 19:33 UTC
As of around https://github.com/nodejs/node/pull/3599, `make test-npm` works even without `node` or `npm` in the `PATH`.

npm's legacy tests still require internet, but as a first step, I suggest we disable those and run the tests that don't require internet. (The `tap` tests I believe.)

The windows tests are apparently in pretty bad shape last I heard, so I recommend we start with OS X and then Linux.

cc @othiym23, @zkat, @iarna, @jasnell?

**Comment by maclover7** [comment] 2017-10-15 19:55
Should this be combined with #317 or closed?

**Comment by gibfahn** [comment] 2017-10-16 06:55
Yep, closing as a duplicate of #317 as that one has more info in it.

**Closed by gibfahn** 2017-10-16 06:55 UTC
Labels: jenkins-ci
