### ISSUE TITLE
No nightly or canary builds in the repository since 26-Dec-2022

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/build#3143] opened 2023-01-03 10:09 UTC
Last builds:

https://direct.nodejs.org/download/nightly/v20.0.0-nightly202212267c7d2e8dc6/

https://direct.nodejs.org/download/v8-canary/v20.0.0-v8-canary202212266b2b946a63/

**Comment by targos** [comment] 2023-01-03 10:14
```
07:06:40 mkdir: cannot create directory ‘nodejs/nightly/v20.0.0-nightly202301039eb363a3e0’: No space left on device
```

**Comment by targos** [comment] 2023-01-03 10:14
This is actually a duplicate of https://github.com/nodejs/build/issues/3125

**Closed by targos** 2023-01-03 10:14 UTC
Labels: incident, ci-release
