### ISSUE TITLE
problems with node-test-pull-request

### ISSUE THREAD

**Issue by targos** [nodejs/build#263] opened 2015-11-23 08:02 UTC
The job is malfunctioning.

It either just fails:
https://ci.nodejs.org/job/node-test-pull-request/811/
https://ci.nodejs.org/job/node-test-pull-request/813/

Or only runs the Windows and ARM jobs (which also fail):
https://ci.nodejs.org/job/node-test-pull-request/810/
https://ci.nodejs.org/job/node-test-pull-request/812/
https://ci.nodejs.org/job/node-test-pull-request/814/

**Comment by rvagg** [comment] 2015-11-23 08:56
@joaocgreis looks like the scm change thing is awry again, perhaps an update has fixed the original problem and we need to reverse the option reversal?

**Comment by orangemocha** [comment] 2015-11-23 16:15
The first set of failures seems due to https://issues.jenkins-ci.org/browse/JENKINS-31527. The comments in the issue indicate that this affects version 1.19 of the MultiJob plug-in, but not 1.18.

The second set of failures seems the same as the issue we had last week, where Jenkins was polling for SCM changes even though it's not supposed to. @joaocgreis had fixed it but I don't know all the details.

@nodejs/jenkins-admins did you upgrade any plug-in updates recently?

**Comment by orangemocha** [comment] 2015-11-23 22:55
Disabling the node-test-* jobs while we figure this out, to avoid any false positives.

**Comment by orangemocha** [comment] 2015-11-23 23:20
@nodejs/collaborators Jenkins is not working reliably because of this issue. I have disabled node-test-pull-request and node-test-commit to avoid any false positives while we sort this out.

**Comment by orangemocha** [comment] 2015-11-23 23:55
It seems to be back to normal after downgrading the Multijob plugin to version 1.19 (it has been updated to 1.20). I kicked off 3 builds of node-test-pull-request with different PRs as listed in the description of this issue, to gain some confidence that it's indeed working.

**Comment by orangemocha** [comment] 2015-11-24 04:49
The original issue seems solved after downgrading the multijob plugin to 1.19.

There are still persistent failures in the ARM cross-compile job, which seem unrelated and possibly legitimate as they reproduce on master: https://ci.nodejs.org/job/node-cross-compile/588/nodes=cross-compiler-pi1p/console

**Comment by bnoordhuis** [comment] 2015-11-24 12:31
> /home/iojs/build/workspace/node-cross-compile/nodes/cross-compiler-pi1p/out/Release/mksnapshot: 1: /home/iojs/build/workspace/node-cross-compile/nodes/cross-compiler-pi1p/out/Release/mksnapshot: Syntax error: word unexpected (expecting ")")

Looks to be the result of enabling snapshots in https://github.com/nodejs/node/pull/3962.

**Comment by indutny** [comment] 2015-11-24 17:18
Looking into it.

**Comment by indutny** [comment] 2015-11-24 17:22
From what I just read it seems that `--with-snapshot` is not compatible with cross-building. Should we consider passing extra configure flag on CI instead of reverting it? cc @bnoordhuis @orangemocha

**Comment by indutny** [comment] 2015-11-24 17:22
cc @nodejs/build

**Comment by orangemocha** [comment] 2015-11-24 17:37
Looking into it.

**Comment by orangemocha** [comment] 2015-11-24 17:57
I changed the cross-compile job to pass `--without-snapshot` to `configure`, and it seems to be working: https://ci.nodejs.org/job/node-test-commit-arm-fanned/619/. CI is usable again.

I will open a separate issue to discuss whether it's a good long-term approach.

**Comment by indutny** [comment] 2015-11-24 17:59
Thanks!

**Comment by orangemocha** [comment] 2015-11-24 18:55
Closing as node-test-pull-request is working again. Opened follow-up issues at https://github.com/nodejs/build/issues/265 and https://github.com/nodejs/build/issues/266.

**Closed by orangemocha** 2015-11-24 18:55 UTC
