### ISSUE TITLE
500 Internal Server error downloading node-v16.7.0-linux-x64.tar.gz from nodejs.org

### ISSUE THREAD

**Issue by hfarr** [nodejs/build#3472] opened 2023-08-24 17:20 UTC
https://nodejs.org/dist/v16.7.0/node-v16.7.0-linux-x64.tar.gz is returning a 500 internal server error, and its breaking a CI pipeline. 

So far I've just seen it affecting v16.7.0, even https://nodejs.org/dist/v16.8.0/node-v16.8.0-linux-x64.tar.gz is working

**Comment by gmishkin** [comment] 2023-08-24 17:51
Seeing it with 16.18.0-darwin-arm64.

**Comment by ovflowd** [comment] 2023-08-24 20:46
I assume this is a duplicate of https://github.com/nodejs/nodejs.org/issues/4495

**Closed** 2023-08-26 22:15 UTC
