### ISSUE TITLE
Disk space issues on Mac Machines 

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#3061] opened 2022-10-28 13:35 UTC
We are running out of space on the Mac machines at both NearForm and MacStadium.

I think that we should likely be able to create new vms at MacStadium with larger disks. I think @AshCripps is mentioned he might be able to look at this.  @AshCripps can you comment on this.

The NearForm machines are physical machines so we need to either add additional external drives or get new machines.  

In terms of addings disk lets ask our contact at Nearform what connections are available on the machine as a start

We should also discuss if we should ask for some additional machines with larger disks. @nodejs/build. The wrinkle is wether we'd ask for M1 or intel machines. I think its the intel ones we are having issues on.

**Comment by AshCripps** [comment] 2022-10-28 13:48
The orka macs shouldnt need increased disks they are provisioned with at least 90GB of storage so that should be plenty. The issue is macos is filling up with loads of cache files which need investigating (for example https://github.com/nodejs/build/issues/2917#issuecomment-1290526844 there was one file that was 39GB in size) so imo it makes more sense to figure out how to stop that happening rather than going through the effort of re-provisioning everything.

The nearform macs are different story they always had only about 12GB of headroom on them historically and now the node folder has ballooned to 16GB this isnt enough.

**Comment by efrisby** [comment] 2022-11-03 14:20
If any help is needed from NearForm IT let me know. If drives or changes to machines are needed we should be able to accommodate.

**Comment by mhdawson** [comment] 2022-11-03 18:55
@efrisby can you look and tell us what kind of connectors there are on the machines in terms of being able to add an external disk, usb, sata, both, etc.?

**Comment by sxa** [comment] 2023-09-01 10:31
@UlisesGascon do you know if we still have an issue with this?

**Comment by UlisesGascon** [comment] 2023-09-02 08:58
> @UlisesGascon do you know if we still have an issue with this?

Currently, the machines are more stable in terms of empty space specially for MacStadium ones. So, I assume that we can close this issue for now and reopen if we plan to do changes in the hardware for Nearform ones.

**Closed** 2023-12-21 05:43 UTC
Labels: platform:osx
