### ISSUE TITLE
No nightly tarballs for AIX

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/build#1965] opened 2019-10-17 21:13 UTC
In https://ci.nodejs.org/job/node-test-node-addon-api-new/nodes=aix61-ppc64/781/console it looks like it's failing to download the appropriate Node.js release tarball.

Looks like the nightlies for AIX have been missing for a short while: https://github.com/nodejs/build/issues/1957#issuecomment-543013729

**Comment by rvagg** [comment] 2019-10-18 00:34
missing for 13.0.0-rc\* builds too. @sam-github do you have access to the release machine?

**Comment by sam-github** [comment] 2019-10-18 02:40
Yes I have access, and I believe/hope this is a symptom of https://github.com/nodejs/build/issues/1957#issuecomment-543460591

**Comment by sam-github** [comment] 2019-10-18 15:44
duplicate of https://github.com/nodejs/build/issues/1957

**Closed by sam-github** 2019-10-18 15:44 UTC

**Comment by sam-github** [comment] 2019-10-18 19:12
I built nightlies for 13.x: https://github.com/nodejs/build/issues/1957#issuecomment-543893348

Is that what you need @gabrielschulhof ?

**Comment by gabrielschulhof** [comment] 2019-10-18 20:16
@sam-github I'll check if it causes the build for https://github.com/nodejs/node-addon-api/pull/562 to go green.

**Comment by gabrielschulhof** [comment] 2019-10-18 20:27
@sam-github looks like it moved past the point where it was failing to find the nightly tarball.

**Comment by gabrielschulhof** [comment] 2019-10-18 20:28
Looks like the build will be green 👍 Thanks!
