### ISSUE TITLE
`test-azure_msft-win11_vs2022-arm64-1` is offline

### ISSUE THREAD

**Issue by targos** [nodejs/build#3943] opened 2024-10-30 13:13 UTC
https://ci.nodejs.org/computer/test-azure_msft-win11_vs2022-arm64-1/

@StefanStojanovic

**Comment by StefanStojanovic** [comment] 2024-11-04 09:44
The same issue appeared on other Windows 11 ARM64 machines. It was most likely caused by the Temurin update. All of the nodes are now back online and are no longer experiencing that behavior. Closing the issue.

**Closed by StefanStojanovic** 2024-11-04 09:44 UTC
Labels: incident, platform:windows
