### ISSUE TITLE
Windows permanently-failing-in-CI hosts marked offline

### ISSUE THREAD

**Issue by Trott** [nodejs/build#2145] opened 2020-01-25 18:12 UTC
To get CI working, I marked four Windows hosts as offline. They were failing CI tests consistently.

* test-rackspace-win2008r2_vs2017-x64-1 
* test-azure_msft-win10_vs2019-x64-4
* test-rackspace-win2012r2_vs2019-x64-2
* test-azure_msft-win2016_vs2017-x64-3

Not sure what the right thing to do to get them back online is.

**Comment by Trott** [comment] 2020-01-25 23:36
It seems to be spreading...now adding:

* test-azure_msft-win10_vs2019-x64-1
* test-azure_msft-win10_vcbt2015-x64-3
* test-rackspace-win2008r2_vs2017-x64-3
* test-rackspace-win2008r2_vs2017-x64-2
* test-rackspace-win2012r2_vs2019-x64-1 
* test-rackspace-win2012r2_vs2017-x64-3
* test-rackspace-win2012r2_vs2013-x64-2 
* test-azure_msft-win2016_vs2017-x64-4
* test-azure_msft-win2016_vs2017-x64-5
* test-azure_msft-win2016_vs2017-x64-1

Hoping there are still some windows hosts left to run tests...

/ping @joaocgreis

**Comment by Trott** [comment] 2020-01-25 23:38
* win2008r2_vs2017-x64-3

**Comment by joaocgreis** [comment] 2020-01-27 00:37
This was apparently caused by an old version of https://github.com/nodejs/node/pull/31505 leaving behind files that could not be removed by git clean.

The PR is now fixed, the computers clean and back online, and windows-fanned back to green.

@Trott thanks for taking the machines offline! Another thing that might or might not help but should be harmless is to run https://ci.nodejs.org/view/All/job/git-clean-windows/ and https://ci.nodejs.org/view/All/job/windows-update-reboot/ with force reboot.

**Closed by joaocgreis** 2020-01-27 00:37 UTC
Labels: platform:windows

**Comment by Trott** [comment] 2020-01-27 02:39
> Another thing that might or might not help but should be harmless is to run https://ci.nodejs.org/view/All/job/git-clean-windows/ and https://ci.nodejs.org/view/All/job/windows-update-reboot/ with force reboot.

I didn't know those existed! I'll try them next time I'm completely flummoxed by a Windows issue and have no idea what to do. :-D

Thanks!

**Comment by richardlau** [comment] 2020-01-30 16:36
Maybe add those to https://github.com/nodejs/build/blob/master/doc/jenkins-guide.md#solving-problems?

**Comment by Trott** [comment] 2020-02-18 06:39
> Maybe add those to https://github.com/nodejs/build/blob/master/doc/jenkins-guide.md#solving-problems?

https://github.com/nodejs/build/pull/2181
