### ISSUE TITLE
Managing optional dependencies

### ISSUE THREAD

**Issue by orangemocha** [nodejs/build#310] opened 2016-01-20 10:20 UTC
For icu data and other optional dependencies (eg https://github.com/nodejs/node/pull/4765#issuecomment-172961048), concerns have been raised about having dependencies that are rarely used bloat the size of the main node repo.

We solved this for icu by making the data a downloadable component rather than checking it into git. I am wondering if we can find a solution to this problem that ensures adequate versioning semantics while permitting to fetch the dependency only when necessary.

**Comment by orangemocha** [comment] 2016-01-20 10:23
In the past I had researched a few git-based solutions, in particular:

1. [git submodule](https://git-scm.com/docs/git-submodule)
2. [git subtree](https://git-scm.com/book/en/v1/Git-Tools-Subtree-Merging)
3. This simple script: http://blog.rusty.io/2010/01/24/submodules-and-subrepos-done-right/

Both submodules and subtree seemed to introduce more problems than they solve. The script approach at 3. looked promising.

**Comment by panuhorsmalahti** [comment] 2016-01-20 16:41
What exactly are the problems with git submodules?

**Comment by bnoordhuis** [comment] 2016-01-20 17:11
Everything takes more work: `git submodule foreach git grep ...`, `git pull && git submodule update --recursive`, etc.  Bisecting across submodules is cumbersome as well.

I, for one, like our big monorepo, size be damned.

**Comment by MrRio** [comment] 2016-01-20 17:34
Google have their entire infrastructure, every product, in one repo.

It's easier to branch and make sweeping changes.

**Comment by panuhorsmalahti** [comment] 2016-01-20 18:03
@bnoordhuis Having to make sync commits manually also takes work. I work with submodules daily and I find them trivial, especially if the depth of submodules is only one and there are no complex relationships/duplicates of submodules.

@MrRio I support monorepositories if the monorepository is not a duplicate of another, "master" repository. Atomic commits across multiple codebases is an attractive feature, but from what I gather not that useful in Node.js.

**Comment by Arthur2e5** [comment] 2016-01-21 05:28
As far as I know both 'solutions' 2 and 3 still involves checking the whole thing into git, and always fetching them when cloning.

* * *

In solution 3 the changesets are stored twice which introduces some redundancy:

1. The `.subgit` directory (you still have to find somewhere to host it).
2. The big repo directory. Every time you do `subgit pull`, you get a big set of changes which is essentially a combined result of the changes made since the last `pull`. People want to keep the deps up to date, so you will end up having trunks of big commits (a bit 'shallower' indeed).

* * *

Solution 2, the `subtree` solution (including the git/contrib/git-subtree wrapped one) doesn't show significant difference from the current method, since you are still essentially pointing the trees as if they are put here normally, only with some extra caution so they can still correspond to somewhere else in this `.git` dir or some other repos in the future.

https://schacon.github.io/git/git-read-tree.html#_sparse_checkout looks interesting though.

* * *

Submodule is the right way to go IMHO. All those extra mess is simply caused by you trying to having more control over what to fetch. But if you simply want to fetch everything, you can just go for `git clone --recursive`.  There is even `git submodule update --depth 1` which allows you to save some time loading the dependencies.

Oh, and.. The [git-subtree](https://github.com/git/git/blob/master/contrib/subtree/git-subtree.sh) script can be quite handy for spliting new repos from existing directories. For example, I don't think chakrashim is hosted independently anywhere else and you may still want to split it out so everything looks like submodules.

* * *
 
@bnoordhuis That's a valid point, but since nodejs is now focusing on submodule-ing out dependencies which is not a main focus of bisecting, I'd rather say this problem is not that big.

`git bisect` does checks out `.gitmodules` and these `Subproject commit <SHA1>`  info of that commit , and one can still figure out which commit *nodejs developers* made included something bad from dependencies by running tests after doing submodule 'updates'. Careful bisecting in that specific submodule with the outside source being unchanged can be done afterwards. 

If the developers of those dependencies are doing their job well, this actually filters out some noise.

**Comment by jbergstroem** [comment] 2016-01-21 05:37
@Arthur2e5 as far as I know nodejs hasn't taken a decision on whether we should use submodules or not (or am I missing something?).

**Comment by Arthur2e5** [comment] 2016-01-21 05:40
Yes, just prefix everything with *suppose*…

**Comment by boopathi** [comment] 2016-01-21 08:19
Could something like gclient (https://www.chromium.org/developers/how-tos/depottools) help ?

**Comment by Fishrock123** [comment] 2016-01-21 17:14
Also keep in mind that we may have to float patches on our deps (optional or not)

**Comment by TheAlphaNerd** [comment] 2016-01-21 17:34
One thing to consider about submodules, they do not necessarily help with size. 

Perhaps they do help take down the burden of the initial size, but the eventual download is much higher if you are cloning a submodule with the entire history of the dependency.

For context, the ChakraCore git module is about 140 megabytes, it goes down to 100 if you simply copy the assets without the .git folder (70 of which is in the tests folder).

This discrepancy is only going to get larger as the project moves forward (for example the v8 repo is over 4GB and only 88 MB in the node.js repo. Obviously there is more than 88 MB worth of information tracked in the repo, but I doubt we have 4 GB as the node repo is 1.5 GB

All of this is still missing when this is often done in practice, which is during compilation, which can often happen in a tar ball with no .git folder.

**Comment by Trott** [comment] 2018-03-30 21:36
@nodejs/build Should this remain open?

**Comment by Trott** [comment] 2018-03-30 23:40
I'm going to close this for now because it seems like we're not going to change anything. If I'm wrong about that and/or this should be open for another reason, feel free to re-open or comment.

**Closed by Trott** 2018-03-30 23:40 UTC
