### ISSUE TITLE
V8 CI is not working

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#886] opened 2017-09-16 22:59 UTC
Looks like an error with glient fetching v8

```
Fetching V8 from chromium.googlesource.com
Error: Command 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' returned non-zero exit status 1 in /home/iojs/build/workspace/node-test-commit-v8-linux/nodes/ppcle-ubuntu1404/v8test/v8test/deps
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "managed": False,
    "name": "v8",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
Running: gclient sync --with_branch_heads
Traceback (most recent call last):
  File "/home/iojs/build/workspace/node-test-commit-v8-linux/nodes/ppcle-ubuntu1404/v8test/v8test/depot_tools/fetch.py", line 299, in <module>
    sys.exit(main())
  File "/home/iojs/build/workspace/node-test-commit-v8-linux/nodes/ppcle-ubuntu1404/v8test/v8test/depot_tools/fetch.py", line 294, in main
    return run(options, spec, root)
  File "/home/iojs/build/workspace/node-test-commit-v8-linux/nodes/ppcle-ubuntu1404/v8test/v8test/depot_tools/fetch.py", line 288, in run
    return checkout.init()
  File "/home/iojs/build/workspace/node-test-commit-v8-linux/nodes/ppcle-ubuntu1404/v8test/v8test/depot_tools/fetch.py", line 131, in init
    self.run_gclient(*sync_cmd)
  File "/home/iojs/build/workspace/node-test-commit-v8-linux/nodes/ppcle-ubuntu1404/v8test/v8test/depot_tools/fetch.py", line 78, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "/home/iojs/build/workspace/node-test-commit-v8-linux/nodes/ppcle-ubuntu1404/v8test/v8test/depot_tools/fetch.py", line 68, in run
    return subprocess.check_output(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('gclient', 'sync', '--with_branch_heads')' returned non-zero exit status 2
V8 fetch failed
```

/cc @mhdawson @nodejs/v8

**Comment by MylesBorins** [comment] 2017-09-16 22:59
Worth mentioning this is happening for any + all attempts to run CI right now

**Comment by gibfahn** [comment] 2017-09-16 23:09
To be clear, this is happening for all runs of [node-test-commit-v8-linux](https://ci.nodejs.org/job/node-test-commit-v8-linux/), not `node-test-commit` right?

@joransiu @jbarz do I recall you guys talking about something like this on Slack?

**Comment by jbajwa** [comment] 2017-09-17 12:43
This started failing after https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/656565.
@john-yan is working with chromium's infra team on this https://bugs.chromium.org/p/chromium/issues/detail?id=764087 . In the meantime could add the following to the jenkins job
```
cd <path>/depot_tools
git revert -n 509776e
cd -
export DEPOT_TOOLS_UPDATE=0
```

**Comment by mhdawson** [comment] 2017-09-18 13:28
Have put the work around into the job and kicked off a run to see if it resolves the issue.

**Comment by gibfahn** [comment] 2017-09-18 15:46
Assuming it's https://ci.nodejs.org/job/node-test-commit-v8-linux/912/ then it looks like it worked.

We should leave this open to track the proper fix though, sounds like John is making progress.

**Comment by mhdawson** [comment] 2017-09-18 16:05
Looks like work around did the trick, lets leave this open until the proper fix is in place.

**Comment by mhdawson** [comment] 2017-10-03 19:52
@jbarz @joransiu this looks different than this issue https://bugs.chromium.org/p/chromium/issues/detail?id=764087&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=

But it did remind me to ask where we are on this one.  At some point I should remove the work around.

**Comment by john-yan** [comment] 2017-10-03 20:11
It should be fixed now. All we need to do is adding an extra env variable.
export VPYTHON_BYPASS="manually managed python not supported by chrome operations"

**Comment by MylesBorins** [comment] 2017-10-09 20:14
Looks like the temporary patch is now failing 😭

I'm hacking on the CI job right now to make a permanent fix

**Comment by MylesBorins** [comment] 2017-10-09 21:01
Was not able to fix it. I attempted to revert all of the hacks we had currently put in and added `export VPYTHON_BYPASS="manually managed python not supported by chrome operations"`

Same error reported in OP

**Comment by refack** [comment] 2017-10-09 21:23
The error I'm seeing is:
```
[iojs@test-rackspace-fedora24-x64-1 deps]$ /usr/bin/python v8/third_party/binutils/download.py
Downloading /home/iojs/build/workspace/node-test-commit-v8-linux-fedora24/nodes/fedora24/v8test/v8test/deps/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
Traceback (most recent call last):
  File "v8/third_party/binutils/download.py", line 117, in <module>
    sys.exit(main(sys.argv))
  File "v8/third_party/binutils/download.py", line 106, in main
    return FetchAndExtract(arch)
  File "v8/third_party/binutils/download.py", line 81, in FetchAndExtract
    '-s', sha1file])
  File "/usr/lib64/python2.7/subprocess.py", line 536, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```
Using https://ci.nodejs.org/job/node-test-commit-v8-linux-fedora24/nodes=fedora24,v8test=v8test/398/console as referance.
Manual on `test-rackspace-fedora24-x64-1`

**Comment by refack** [comment] 2017-10-09 22:29
Ok found some stuff:
1. The fedora machines (https://ci.nodejs.org/job/node-test-commit-v8-linux-fedora24/) are failing because they don't have `bzip2` (and their yum repos have been archived to http://archives.fedoraproject.org/pub/archive/fedora/linux), but I see this is only run by timer...
2. ppc getting:
   ```
   iojs@test-osuosl-ubuntu14-ppc64-be-3:~/build/workspace/node-test-commit-v8-linux/nodes/ppcbe-
   ubuntu1404/v8test/v8test/depot_tools$ ./update_depot_tools
   UNKNOWN Machine architecture: ppc64
   ```
   which lead me to https://bugs.chromium.org/p/chromium/issues/detail?id=764087.
   I think it's a `depot_tools` regression of that issue.

---

The best I got is to revive the test on the `fedora24` - https://ci.nodejs.org/job/node-test-commit-v8-linux-fedora24/399/nodes=fedora24,v8test=v8test/

**Comment by MylesBorins** [comment] 2017-10-09 23:02
@refack were you testing with `VPYTHON_BYPASS="manually managed python not supported by chrome operations"`

**Comment by refack** [comment] 2017-10-09 23:08
> @refack were you testing with VPYTHON_BYPASS="manually managed python not supported by chrome operations"

In multiple variations with no success (with `"` without, in the same line, with `export`, before `make` after `make`, with just calling
Also it wasn't there yesterday when the last green job run https://ci.nodejs.org/view/All/job/node-test-commit-v8-linux/953/nodes=ppcbe-ubuntu1404,v8test=v8test/consoleFull

But now I see that we used to roll back `depot_tools`, and it broke sometime in the last 24h:
```
+ git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
Cloning into 'depot_tools'...
+ cd depot_tools
+ git revert -n 509776e
error: could not revert 509776e... [gsutil] run through "vpython" (2)
hint: after resolving the conflicts, mark the corrected paths
```

**Comment by refack** [comment] 2017-10-09 23:26
@MylesBorins need someone with job edit capas.
add this
`git checkout 633a9830a9fce875d277b248c6e6fb14d72e8183`
just after
`cd depot_tools`
and before
`git revert -n 509776e`

That should do it.

**Comment by gibfahn** [comment] 2017-10-09 23:32
>@MylesBorins need someone with job edit capas.

My copy and paste skills are on point

**Comment by gibfahn** [comment] 2017-10-09 23:34
https://ci.nodejs.org/view/All/job/node-test-commit-v8-linux/962/

New log:

```bash

**Comment by refack** [comment] 2017-10-09 23:48
sorry new SHA - 77b7687e4837223f820e1e98c369d36696f3f2b3

**Comment by gibfahn** [comment] 2017-10-09 23:52
```bash
git checkout 633a9830a9fce875d277b248c6e6fb14d72e8183
git revert -n 77b7687e4837223f820e1e98c369d36696f3f2b3 || true
```

Seems healthier. Actually the previous SHA was fine, there was a conflict, but we're not committing so not an issue.

https://ci.nodejs.org/view/All/job/node-test-commit-v8-linux/967/ 🙏

**Comment by refack** [comment] 2017-10-10 00:10
I think it should be:
```
git checkout 77b7687e4837223f820e1e98c369d36696f3f2b3
git revert -n 509776e
```
And don't add the ` || true` cause if it fails, it won't build.

**Comment by refack** [comment] 2017-10-10 00:10
P.S. the conflict is the crux of the issue

**Comment by gibfahn** [comment] 2017-10-10 01:37
Okay, my flight is delayed so lots of time to fix this...

Seems to be working better.

**Comment by gibfahn** [comment] 2017-10-10 01:47
FWIW this, and other things like the FreeBSD bugs, are really regressions in V8 and tools on platforms that Node supports but V8 doesn't (so for V8 I guess not technically regressions, but whatever). I'm not really sure how to solve this, but if we're running Node on V8 to make sure V8 commits don't break Node, we should probably think about platform support. Most regressions arent going to be on xLinux or macOS, they're going to be on less-used platforms.

**Comment by refack** [comment] 2017-10-10 02:13
I think we can with not too much effort remove the dependency on `depot_tools`, it's a very fragile monstrosity (this current issue is because of `vpython` which is a frankenstein of `python` and `virtualenv` compiled together in `go` 🤦‍♂️ . For that, depot_tools brings it's own `python`, `clang`, and `go` compiler).

I have a partial recipe for syncing V8 without `depot_tools` (partial as in works-on-my-computer), I can try to mature it a little.

**Comment by refack** [comment] 2017-10-10 02:14
Holly molly! It's green https://ci.nodejs.org/view/All/job/node-test-commit-v8-linux/968/

**Comment by MylesBorins** [comment] 2017-10-10 19:01
Looks like the git changes broke stuff... failures across all environments rn

**Comment by refack** [comment] 2017-10-10 19:34
@MylesBorins that's a `v4.x` PR right? (https://ci.nodejs.org/view/All/job/node-test-commit-v8-linux/970/)
Do we know when was the last known good revision for testing `v4.x`?

**Comment by MylesBorins** [comment] 2017-10-11 07:19
nvm... I think I broke stuff... Will check in again in am and confirm

**Comment by mhdawson** [comment] 2017-10-11 17:00
@john-yan I tried putting in the final fix by adding

```
# temporary work around for https://github.com/nodejs/build/issues/886
#export DEPOT_TOOLS_UPDATE=0 
export VPYTHON_BYPASS="manually managed python not supported by chrome operations"
```

But it is still failing on the PPC platforms.  See this job which is a clone of the regular CI job with the change in place:

https://ci.nodejs.org/view/All/job/node-test-commit-v8-linux-test-mdawson/configure

**Comment by mhdawson** [comment] 2017-10-11 19:20
Is it just me or does it look like the job is no longer running all of the tests ?

**Comment by mhdawson** [comment] 2017-10-11 19:32
Ignore my last comment, its just that they run in the middle of the job since there is recompilation for the hashseed test.

**Comment by john-yan** [comment] 2017-10-11 22:18
open https://bugs.chromium.org/p/chromium/issues/detail?id=773857 to fix depot_tools on ppc

**Comment by john-yan** [comment] 2017-10-17 20:15
Hello, depot_tools should be fixed on ppc linux now.
```
>fetch v8
Running: gclient root
Running: gclient config --spec 'solutions = [
  { 
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "managed": False,
    "name": "v8",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
Running: gclient sync --with_branch_heads
Running: git submodule foreach 'git config -f $toplevel/.git/config submodule.$name.ignore all'
Running: git config --add remote.origin.fetch '+refs/tags/*:refs/tags/*'
Running: git config diff.ignoreSubmodules all
```

**Comment by refack** [comment] 2017-10-17 20:42
crbug pretty much resolved. we can remove the `git checkout` and `git revert` and instead add:
`export VPYTHON_BYPASS="manually managed python not supported by chrome operations"`

/cc @mhdawson @gibfahn

**Comment by refack** [comment] 2017-10-17 20:43
Thank @john-yan 🎉

**Comment by mhdawson** [comment] 2017-10-18 14:13
Tested here: https://ci.nodejs.org/view/All/job/node-test-commit-v8-linux-test-mdawson/8/

**Comment by mhdawson** [comment] 2017-10-18 14:18
Main job updated, run to validate works as expected: https://ci.nodejs.org/job/node-test-commit-v8-linux/999/

**Comment by mhdawson** [comment] 2017-10-18 14:41
Looks good closing.

**Closed** 2017-10-19 11:40 UTC
