### ISSUE TITLE
ImportError: No module named 'tap13' on ubuntu1604_sharedlibs_debug_x64

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#1832] opened 2019-06-11 00:54 UTC
Recent `ubuntu1604_sharedlibs_debug_x64` jobs are failing with the following error:
e.g. https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu1604_sharedlibs_debug_x64/13339/console
```console
20:33:15 + mkdir out/junit
20:33:15 + tap2junit -i test.tap -o out/junit/test.xml
20:33:15 Traceback (most recent call last):
20:33:15   File "/usr/local/bin/tap2junit", line 7, in <module>
20:33:15     from tap2junit.__main__ import main
20:33:15   File "/usr/local/lib/python3.5/dist-packages/tap2junit/__main__.py", line 5, in <module>
20:33:15     from tap13 import TAP13 as tap13
20:33:15 ImportError: No module named 'tap13'
20:33:15 POST BUILD TASK : FAILURE
```

**Comment by rvagg** [comment] 2019-06-11 02:43
dupe of #1830 I believe, it looks like we have python 3.5 compatibility problems here, but why is this new?

**Closed** 2019-06-11 02:45 UTC
