### ISSUE TITLE
Build on Github Action test-macOS frequently fail due machine run out of disk space

### ISSUE THREAD

**Issue by jakecastelli** [nodejs/build#3878] opened 2024-08-30 04:07 UTC
The Github Actions start to fail frequently on **_test-macOS_** build step due to the current build on mac is about 18GB which seems more than the allocated disk space on the runner (14GB limit IIRC). See [this](https://github.com/nodejs/node/actions/runs/10620801746) for a failure example:

> [test-macOS](https://github.com/nodejs/node/actions/runs/10620801746/job/29441356276#step:1:28)
You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 47 MB

This currently impacts all the Pull Requests on nodejs cores.

**Comment by targos** [comment] 2024-08-30 13:08
Should we disable macOS jobs for now?

**Comment by targos** [comment] 2024-08-30 13:10
The problem is that we would have 0 CI coverage for arm64 macOS if we do it (Jenkins CI currently only tests on x64)

**Comment by jakecastelli** [comment] 2024-08-30 13:49
Do we need Android sdk for macOS arm64 build? Any chance we can temporarily remove it (with a quick patch) from the `test-macOS` job? seems like it can claim back ~12GB storage space.

**Comment by targos** [comment] 2024-09-01 09:37
Fixed by https://github.com/nodejs/node/pull/54658

**Closed by targos** 2024-09-01 09:37 UTC
Labels: platform:osx
