### ISSUE TITLE
Issues with Raspberry Pi 

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1099] opened 2018-02-01 12:46 UTC
At least on two builds all Raspberry Pi 1 had issues that I guess are build related: https://ci.nodejs.org/job/node-test-binary-arm/13297/

And some tests show that there is no space left on the devices on Raspberry Pi  3:
https://ci.nodejs.org/job/node-test-binary-arm/13297/RUN_SUBSET=3,label=pi3-raspbian-jessie/console

```
06:22:49     AssertionError [ERR_ASSERTION]: ifError got unwanted exception: ENOSPC: no space left on device, fchmod
```

**Comment by joyeecheung** [comment] 2018-02-01 14:52
cc @rvagg 

I am wondering what are the steps to fix this? Are they written down somewhere so the next time this happens one of us can clean up the disk asap?

**Comment by rvagg** [comment] 2018-02-06 21:01
`ENOSPC` is hardly ever about running out of space, that particular Pi is just fine in terms of disk space. How could `fchmod` even result in running out of space? It's one of the most frustrating error that libuv throws up cause it's hard to figure out what the cause is. I'll see if I can work this out later today but if we're having persistent problems we may need to remove arm-fanned from test-commit for now.

**Comment by maclover7** [comment] 2018-05-22 22:04
ping -- is this still an issue?

**Comment by maclover7** [comment] 2018-05-24 21:53
Closing due to these errors largely not appearing anymore, and Pi builds are more stable

**Closed by maclover7** 2018-05-24 21:53 UTC
