### ISSUE TITLE
Can 'make lint-py PYTHON=python3' be a manditory Jenkins test?

### ISSUE THREAD

**Issue by cclauss** [nodejs/build#1631] opened 2018-12-11 12:13 UTC
**Is your feature request related to a problem? Please describe.**
__Python 2 end-of-life is one year from now__.  We have been working for a while and this repo's code now contains no Python 3 syntax errors or undefined names.  __make lint-py__ shows that we no longer have any syntax errors on either Python 2 or Python 3.  It also shows that we have fixed all _undefined names_ like __basestring, cmp(), file, reduce(), raw_input(), unicode, xrange()__ that were removed in Python 3.

The port to Python 3 is _not yet complete_ but the codebase is "syntax compatible" which is a state that we should now preserve and guard against any backsliding.

**Describe the solution you'd like**
~After #24954 lands,~ it would be helpful if every Jenkins run _required_ that __make lint-py PYTHON=python2__ and __make lint-py PYTHON=python3__ both pass.  This will ensure that pull requests do not introduce syntax errors (like __print__ without the parens) or undefined names (like __raw_input()__).  This will help as we complete the port.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.
_Going snowboarding._

/cc @nodejs/python

**Comment by targos** [comment] 2018-12-11 14:57
Issue moved to `nodejs/build`

**Comment by cclauss** [comment] 2018-12-11 15:03
This ___has to be run on Python 3___ because flake8 uses CPython to build an Abstract Syntax Tree and then lints the AST.  This is described int the Very Important Note on the top of http://flake8.pycqa.org

That being said, Python 3 was introduced 8+ years ago so today it is quite easy on all OSes to install both legacy Python and Python side-by-side on the same box and then do __python3 -m flake8 [...]__ and __python2 -m flake8 [...]__.

**Comment by Trott** [comment] 2018-12-11 15:58
> I think it would be enough to test only on one host, with a custom job. And when the build supports Python 3, switch the job to use Python 3 fully.

Oh, yeah, maybe we can just install Python 3 on the linter host(s) only and have it run there via a Jenkins config.

**Comment by cclauss** [comment] 2018-12-14 04:43
This effort can proceed when consensus is reached because nodejs/node#24954 has landed and __make lint-py__ passes on Python 3.

**Comment by Trott** [comment] 2018-12-14 04:51
Adding to the Build WG meeting agenda.

**Comment by rvagg** [comment] 2018-12-18 01:11
If it's just for linting then it should be straight forward I think since it's limited to a few hosts.

But ...

> Python 2 end-of-life is one year from now

Yikes .. I didn't know this but it has huge ramifications across the board for us. Some things off the top of my head:

* node-gyp and GYP in general .. I've mostly tuned out of the many attempts to make our GYP Python 3 compatible because it's such a mess (and mostly I'm just cranky at Google for being so terrible at tools—with a combination of pathological NIMBY and "bored of this, let's invent something new"). If Python 2 is genuinely something we shouldn't be relying on in a year, then we need to have a plan to migrate the entire ecosystem to a Python 3 version of GYP. That's going to take some care and skillful planning I think. Maybe it's time to consider a more radical move for addon building? Promote CMake? Revisit Fedor's gyp.js? Something else?
* Our custom Ansible stuff is only partly Python 3 compatible, mostly it works but there are special use cases where it fails still. There's a couple of PRs and issues open on this repo about this. On my macOS machine I get Python 3 with Ansible thanks to brew, but on my Linux machine I get Python 2 with Ansible, because `<reasons>`.

Python 2 is still everywhere. If 2 is EOL so soon, why do we still have this kind of thing:

```
$ lsb_release -d
Description:	Ubuntu 18.04.1 LTS
$ head -1 $(which ansible)
#! /usr/bin/python2
```

Have distros thrown up their hands too? I believe it's possible to install Python 3 on older hosts we maintain, like CentOS 6. Some of them are a bit awkward because a lot of internal tooling on Linux distros use Python so conflicts are really easy.

This feels to me like a big enough problem that it needs needs something at a higher level, a strategic initiative or short-lived working group to sort out all of the issues. Not that I really want to be thinking more than I have to about this mess but the pain is only going to increase. No, I'm not volunteering to lead such an initiative, our strategy of 🙈 🙉 🙊 isn't sustainable though.

**Comment by cclauss** [comment] 2018-12-18 05:44
https://python3statement.org

https://fedoraproject.org/wiki/FinalizingFedoraSwitchtoPython3

* This is not just for linting.  We will need to run parallel tests for many months.  Putting __both__ Python 2 __and__ Python 3 on a single machine is quite easy these days (even on CentOS 6) so my recommendation would be that we put both on lots of build machines, not just on a few.
* Check out the current version of your favorite linux distro as it probably has _Python 3 installed by default_ and not Python 2
    * https://lwn.net/Articles/756628
    * https://travis-ci.org/Mariatta/python_versions_and_distros/builds/469363099#L215
* https://github.com/ansible/ansible is already fully supports Python 3
* https://github.com/chromium/gyp is already syntax compatible with Python 3
* https://github.com/nodejs/node-gyp needs work to become syntax compatible with Python 3
* https://github.com/nodejs/node is syntax compatible with Python 3 but its dependencies need work

Being syntax compatible != fully supporting.

**Comment by JamesMGreene** [comment] 2018-12-18 19:43
> * https://github.com/chromium/gyp is already syntax compatible with Python 3

Note that this is only as of ~1 week ago and it is largely untested.

**Comment by cclauss** [comment] 2018-12-18 23:35
Installing Python 3 on FreeBSD: [__pkg install python3__](https://docs.python.org/3/using/unix.html?highlight=freebsd)

**Comment by rvagg** [comment] 2018-12-18 23:47
https://ci.nodejs.org/job/node-test-linter/24474/console failing with python3

```
10:43:05 python3 -m pip install --upgrade -t tools/pip/site-packages flake8 || \
10:43:05 	python3 -m pip install --upgrade --system -t tools/pip/site-packages flake8
10:43:05 /usr/local/bin/python3: No module named pip
```

...

```
10:44:24 Running C++ linter...
10:44:25 Traceback (most recent call last):
10:44:25   File "tools/cpplint.py", line 6526, in <module>
10:44:25     main()
10:44:25   File "tools/cpplint.py", line 6510, in main
10:44:25     ProcessFile(filename.decode('utf-8'), _cpplint_state.verbose_level)
10:44:25 AttributeError: 'str' object has no attribute 'decode'
10:44:25 gmake: *** [Makefile:1262: tools/.cpplintstamp] Error 1
```

on master, but even if we fix on master we need a strategy for older branches - do we backport? or do we hack CI to switch python version for older branches?

**Comment by rvagg** [comment] 2018-12-18 23:58
added py36-pip to the install list which cleaned up the first one, second one remains:

```
10:57:11 Running C++ linter...
10:57:12 Traceback (most recent call last):
10:57:12   File "tools/cpplint.py", line 6526, in <module>
10:57:12     main()
10:57:12   File "tools/cpplint.py", line 6510, in main
10:57:12     ProcessFile(filename.decode('utf-8'), _cpplint_state.verbose_level)
10:57:12 AttributeError: 'str' object has no attribute 'decode'
10:57:12 gmake: *** [Makefile:1262: tools/.cpplintstamp] Error 1
```

**Comment by cclauss** [comment] 2018-12-19 00:00
Running an outa date version of cpplint.py

**Comment by rvagg** [comment] 2018-12-19 00:03
so we need to fix that on master then?

**Comment by cclauss** [comment] 2018-12-19 00:08
Why are we bothering with C++?

We merely want the __flake8__ jobs to run on Py2 and Py3.

**Comment by rvagg** [comment] 2018-12-19 00:30
because they're all tangled together:

```sh
which gmake &>/dev/null && MAKE=gmake || MAKE=make
PYTHON=python2

$MAKE lint-md-build PYTHON=$PYTHON || true
$MAKE lint-py-build PYTHON=$PYTHON || true
# If lint-ci fails, print all the interesting lines to the console.
# FreeBSD sed can't handle \s, so use gsed if it exists.
which gsed &>/dev/null && SED=gsed || SED=sed
$MAKE lint-ci PYTHON=$PYTHON || { 
  cat test-eslint.tap | grep -v '^ok\|^TAP version 13\|^1\.\.' | $SED '/^\s*$/d' && 
  exit 1; }
```

We run `lint-ci` which is:

```
lint-ci: lint-js-ci lint-cpp lint-py lint-md lint-addon-docs
```

So this doesn't sound like it's a nodejs/build problem until nodejs/node has Makefile, or cpplint.py, or whatever else sorted out. Then that's going to need to be backported to the supported release lines or we're going to need to add complex version switching logic in our linting job in CI.

**Comment by cclauss** [comment] 2018-12-19 00:49
Let's make two variables __$PYTHON2__and __$PYTHON3__.

**Comment by cclauss** [comment] 2018-12-19 00:53
__cpplint__ @ https://github.com/google/styleguide and https://github.com/cpplint/cpplint are both compatible with Py2 and Py3

**Comment by cclauss** [comment] 2018-12-20 08:37
For now, can we merely add the command __make lint-py PYTHON=python3__ ?

**Comment by cclauss** [comment] 2019-01-21 09:02
With 345 days until [Python 2 end of life](https://twitter.com/raymondh/status/1080961135493316608), where are we at on this issue?

@thefourtheye

**Comment by thefourtheye** [comment] 2019-01-21 14:34
@cclauss I don't have access to build machines yet. But as per https://github.com/nodejs/build/pull/1657/files#diff-057d461401b6960ca924a8e3d864e98cR27 (Meeting notes for Build WG's 2019-01-08 meeting), there is some work to setup Python3 in one of the build machines. I think it is referring to https://github.com/nodejs/build/pull/1644.

**Comment by refack** [comment] 2019-01-21 17:06
As per: https://github.com/nodejs/build/pull/1644#issuecomment-456140612 job can't go live until lint issue is solved in node core (Ref: https://github.com/nodejs/node/pull/25614)

**Comment by refack** [comment] 2019-01-21 17:08
I'm removing from agenda since the specific issue has a clear path to resolution.
Bigger issue addressed in https://github.com/nodejs/TSC/issues/642.

**Comment by thefourtheye** [comment] 2019-01-23 13:15
> As per: #1644 (comment) job can't go live until lint issue is solved in node core (Ref: nodejs/node#25614)

@refack Now that we do not lint python scripts in test/fixtures (ref: https://github.com/nodejs/node/pull/25639), can we push the job to live?

**Comment by mhdawson** [comment] 2019-01-25 20:44
@refack do you already have the job ready to go and we just need to add it to the regressions runs or is there more to do beyond that assuming that we are ready to go given nodejs/node#25639

**Comment by refack** [comment] 2019-01-25 20:52
Ready to go. I just wanted the patched code in `master` to get to as many people as possible.
(Still PR that were not rebased will fail linting, so I was hoping to minimize noise)

**Comment by refack** [comment] 2019-01-25 23:49
> Ok so you are planning to turn it on in a few days or a week at most?

At most. I'll send a PSA now.

**Comment by refack** [comment] 2019-01-26 15:36
Activated for `node-test-linter` (part of `node-test-pull-request`) -> https://ci.nodejs.org/job/node-test-linter/25180/console

Testing job for `node-linter` (part of `node-test-pull-request-lite-pipeline`) -> https://ci.nodejs.org/job/refack-node-linter/2/console

**Comment by cclauss** [comment] 2019-01-26 15:44
Thanks massively...  This will help us avoid any backsliding.

**Comment by Trott** [comment] 2019-01-26 20:42
Closable now? Or is there still more to be done?

**Comment by cclauss** [comment] 2019-03-04 18:55
Can we _please_ get this resolves and closed? 303 daze left...

**Comment by Trott** [comment] 2019-03-04 22:17
(Adding `build-agenda` so it gets discussed at the next Build meeting if there isn't any significant progress between now and then.)

**Comment by refack** [comment] 2019-03-04 22:20
IMO fixing the pipeline job has low ROI. It's mostly a convenience the main job (https://ci.nodejs.org/job/node-test-linter/) runs python linting with Python3, so we have regression testing.

If someone wants to follow up with porting https://github.com/nodejs/build/blob/master/jenkins/pipelines/node-linter.jenkinsfile, that will be very helpful.

**Comment by cclauss** [comment] 2019-06-27 10:27
@rvagg @thefourtheye How do we progress this?

**Closed** 2020-01-28 18:10 UTC
Labels: ci-change, ci-job-request, ci-public
