### ISSUE TITLE
node-test-node-addon-api-new job hanging?

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/build#2131] opened 2020-01-14 16:30 UTC
It seems like this job is regularly hanging - previous runs have taken between 2-10minutes. The previous run took 7 hours+ and the current run is at 4+ hours.

https://ci.nodejs.org/job/node-test-node-addon-api-new/nodes=fedora-latest-x64/1617/

**Comment by BethGriggs** [comment] 2020-01-14 17:32
The same test hang across multiple platforms - possibly caused by https://github.com/nodejs/node/commit/689ab46c646bc8add5560a606ba73d3760f8f924? 

```
AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

  Comparison {
+   message: 'Invalid argument',
+   name: 'Error'
-   message: 'Maximum BigInt size exceeded',
-   name: 'RangeError'
  }
    at test (/home/iojs/build/workspace/node-test-node-addon-api-new/nodes/centos7-ppcle/node-addon-api/test/bigint.js:48:10)
    at Object.<anonymous> (/home/iojs/build/workspace/node-test-node-addon-api-new/nodes/centos7-ppcle/node-addon-api/test/bigint.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:1215:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1235:10)
    at Module.load (internal/modules/cjs/loader.js:1064:32)
    at Function.Module._load (internal/modules/cjs/loader.js:959:14)
    at Module.require (internal/modules/cjs/loader.js:1104:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /home/iojs/build/workspace/node-test-node-addon-api-new/nodes/centos7-ppcle/node-addon-api/test/index.js:96:5
    at Array.forEach (<anonymous>) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: Error: Invalid argument
      at getActual (assert.js:688:5)
      at Function.throws (assert.js:828:24)
      at test (/home/iojs/build/workspace/node-test-node-addon-api-new/nodes/centos7-ppcle/node-addon-api/test/bigint.js:48:10)
      at Object.<anonymous> (/home/iojs/build/workspace/node-test-node-addon-api-new/nodes/centos7-ppcle/node-addon-api/test/bigint.js:6:1)
      at Module._compile (internal/modules/cjs/loader.js:1215:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1235:10)
      at Module.load (internal/modules/cjs/loader.js:1064:32)
      at Function.Module._load (internal/modules/cjs/loader.js:959:14)
      at Module.require (internal/modules/cjs/loader.js:1104:19)
      at require (internal/modules/cjs/helpers.js:72:18),
  expected: [Object],
  operator: 'throws'
}
```

ping @nodejs/addon-api

**Comment by BethGriggs** [comment] 2020-01-14 17:34
Aborted https://ci.nodejs.org/job/node-test-node-addon-api-new/1616/ and https://ci.nodejs.org/job/node-test-node-addon-api-new/1617/ as they were both hanging.

**Comment by richardlau** [comment] 2020-01-14 19:37
> ping @nodejs/addon-api

Based on the team members of https://github.com/nodejs/node-addon-api maybe also ping @nodejs/n-api?

**Comment by BethGriggs** [comment] 2020-01-14 20:42
Does it make sense to turn the timer off on that job until the hanging issue is resolved? I think it is configured to run daily.

**Comment by richardlau** [comment] 2020-01-14 21:24
@nodejs/n-api-admins Are there any objections to enabling timeouts on the job to prevent hanging tests from tying up CI infrastructure? 
![image](https://user-images.githubusercontent.com/5445507/72383797-1a663180-3714-11ea-8db0-8418047dc4dc.png)

**Comment by mhdawson** [comment] 2020-01-15 15:00
I'll try to look today to see if its the BigInt change and if we need to update the tests.

**Comment by mhdawson** [comment] 2020-01-15 15:01
Cancelled the current job

**Comment by mhdawson** [comment] 2020-01-15 15:19
Started by removing 8.x from the tests as is has gone EOL and therefore we've landed some code that no longer works there.

**Comment by mhdawson** [comment] 2020-01-15 15:20
Next will look at the test so that it accomodates the change in master.

**Comment by richardlau** [comment] 2020-01-15 15:28
@mhdawson @nodejs/n-api-admins Any comments on adding a timeout to the node-test-node-addon-api-new build (https://github.com/nodejs/build/issues/2131#issuecomment-574380713)?

I've also noticed that node-test-node-addon-api-new runs once a day on the sixth hour:
![image](https://user-images.githubusercontent.com/5445507/72446298-38cb3c00-37ab-11ea-905c-45c03a18df46.png)

but it's also run once per day by node-test-node-addon-api-LTS versions on the third hour:
![image](https://user-images.githubusercontent.com/5445507/72446357-55677400-37ab-11ea-837f-5b465fc9f4d6.png)

(e.g. for today https://ci.nodejs.org/job/node-test-node-addon-api-new/1625/ and https://ci.nodejs.org/job/node-test-node-addon-api-new/1623/ (via https://ci.nodejs.org/job/node-test-node-addon-api-LTS%20versions/617/))

Does master need to be tested twice a day?

**Comment by mhdawson** [comment] 2020-01-15 20:27
PR to fix test: https://github.com/nodejs/node-addon-api/pull/649

Believe it was also likely the cause of the hang.

**Comment by mhdawson** [comment] 2020-01-15 21:31
Landed PR to fix test.

Updated the new job to not run on its own so we should now only test master once a day

Launched job to test across versions to confirm we are now good
https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-node-addon-api-LTS%20versions/618/

**Comment by mhdawson** [comment] 2020-01-15 22:40
CI run was good across all versions, closing.

@richardlau I'm ok if you enable the option to abort if stuck.

**Comment by richardlau** [comment] 2020-01-15 23:18
Done: https://ci.nodejs.org/job/node-test-node-addon-api-new/jobConfigHistory/showDiffFiles?timestamp1=2020-01-15_16-24-35&timestamp2=2020-01-15_18-16-18

Added a no activity 3600 second (1 hour) time out.

**Closed by richardlau** 2020-01-15 23:18 UTC
