### ISSUE TITLE
Downloads of binaries from nodejs.org are slow / not working

### ISSUE THREAD

**Issue by watson** [nodejs/build#1993] opened 2019-10-23 14:22 UTC
All binary downloads from nodejs.org are very slow currently. E.g. `https://nodejs.org/dist/v13.0.1/node-v13.0.1-darwin-x64.tar.xz`.

In many cases, they will time out, which affects CI systems like Travis who rely on nvm to install Node.js.

According to @targos, the CPU of the server is spinning 100% being used by nginx, but we can't figure out what's wrong.

**Comment by targos** [comment] 2019-10-23 14:23
Top of the `top`:
![image](https://user-images.githubusercontent.com/2352663/67402854-72781680-f5b1-11e9-8831-87b6c8fc1ead.png)

**Comment by targos** [comment] 2019-10-23 14:26
@nodejs/build-infra

**Comment by atulmy** [comment] 2019-10-23 14:40
Same here, using [tj/n](https://github.com/tj/n), the download just terminates after a while

<img width="826" alt="Screenshot 2019-10-23 at 8 09 52 PM" src="https://user-images.githubusercontent.com/685786/67404486-191fdf80-f5d1-11e9-9dab-503703283688.png">

**Comment by kachkaev** [comment] 2019-10-23 14:54
Azure Devops CI/CD also suffer, because a standard Node.js task gets the binary from nodejs.org.

![Screenshot 2019-10-23 at 15 43 41](https://user-images.githubusercontent.com/608862/67405144-427a4480-f5ac-11e9-93a3-16b07dce3791.png)

Kudos to those who are looking into the CPU usage ✌️  _You'll nail it!_ 🙌

**Comment by sam-github** [comment] 2019-10-23 15:24
@targos what machine is the top output from?

Fwiw, only infra team members are: https://github.com/orgs/nodejs/teams/build-infra/members and Gibson isn't current, he should be removed.

**Comment by sam-github** [comment] 2019-10-23 15:31
It could also be that 13.x is super popular? Hard to know without access to access logs.

@MylesBorins the infrasture team is even less staffed than the build team as a whole, if you wanted to pick that up, it would be :tada: fabulous.

**Comment by mhdawson** [comment] 2019-10-23 15:38
The issue has been the metrics in terms of why they are not on a CDN, @joaocgreis and @rvagg do have an active discussion on what we might do on that front.  

@MylesBorins if you can get help for this specific issue that might be good (please check with @rvagg and @joaocgreis ). Better would be ongoing sustained engagement and contribution to the overall build work.

**Comment by targos** [comment] 2019-10-23 15:44
@sam-github it's from `direct.nodejs.org`. I don't have root access to the machine, so `top` is basically the only thing I could do to help.

**Comment by sam-github** [comment] 2019-10-23 16:02
I don't even have non-root access, I guess you do because you are on the release team.

We'll have to wait for an infra person.

**Comment by mhdawson** [comment] 2019-10-23 16:03
I can help take a look after the TSC meeting.

**Comment by michaelsbradleyjr** [comment] 2019-10-23 16:46
In addition to downloads only intermittently succeeding, when they do succeed it seems that sometimes (?) the bundled `node-gyp` is broken.  I'm seeing that behavior in CI builds on Azure Pipelines.

For linux builds with successful downloads of Node.js v8.x and v10.x, `node-gyp` fails to build sources that were previously unproblematic.

For windows builds with successful downloads of Node.js v8.x and v10.x, I'm seeing errors like this:

```
gyp ERR! stack Error: win-x86/node.lib local checksum 629a559d347863902b81fad9b09ba12d08d939d20a0762578e904c6ee1a7adab not match remote fea7d0c5a94fc834a78b44b7da206f0e60ef11dd20d84dc0d49d57ee77e20e16
```

That is, in the case of windows `node-gyp` doesn't attempt to compile; rather, it fails outright owing to the checksum error.

**Comment by mhdawson** [comment] 2019-10-23 18:04
@michaelsbradleyjr I suspect that the node-gyp failures would have been related to downloading header files.

**Comment by mhdawson** [comment] 2019-10-23 18:08
Was looking into this with @targos.  It seems to have resolved itself at this point. 

Looking at the access logs it was a bit hard to tell if there was more traffic or not as the files for the previous day are compressed. We should be able to compare tomorrow more easily.

**Comment by mhdawson** [comment] 2019-10-23 18:12
Top on the machine looks pretty much the same as it did while there were issues as well

**Comment by rvagg** [comment] 2019-10-23 22:31
hm, that top doesn't look exceptional (load average would have been nice to see though @targos, should be up the top right of top). Cloudflare also monitors our servers for overload and switches between them as needed and they're not recording any incidents. It's true that this is a weak point in our infra and that needing to get downloads fully CDNified is a high priority (and we're working on it but are having trouble getting solid solutions that solve all our needs), but I'm not sure we can fully blame this on our main server, there might be something network-related at play that we don't have insight to.

btw, it's myself and @jbergstroem having the discussion about this @mhdawson, not so much @joaocgreis, although you and he are also in the email chain.

@MylesBorins one thing that has come up that might be relevant to you is that _if_ we can get access to Cloudflare's Logpush feature (still negotiating) then we'd need a place to put logs that they support. GCP Storage is an option for that, so maybe getting hold of some credits may be handy in this instance.

**Comment by mhdawson** [comment] 2019-10-23 22:56
@rvagg sorry right @jbergstroem, got the wrong name.

**Comment by mhdawson** [comment] 2019-10-23 22:57
Possibly unrelated, but I did see a complaint of a completing different site reporting slow traffic around the same time.

**Comment by watson** [comment] 2019-10-24 05:55
I can ask my company if they'd be interested in sponsoring us with a hosted Elasticsearch and Kibana setup that can pull all our logs and server metrics and make them easily accessible. This will also give us the ability to send out alerts etc. Would we be interested in that?

**Comment by bvitale** [comment] 2019-10-24 15:02
Hi folks, this seems to be cropping up again this morning.

**Comment by mhdawson** [comment] 2019-10-24 15:09
Current load average: 

```bash
cat /proc/loadavg
2.12 2.15 1.96 1/240 15965
```

**Comment by mhdawson** [comment] 2019-10-24 15:16
load average seems faily steady:

cat /proc/loadavg
1.76 1.90 1.91 3/252 26955

**Comment by renaudaste** [comment] 2019-10-24 15:26
Hello,
Having the issue again on our Azure pipelines (west europe) :
![image](https://user-images.githubusercontent.com/2787377/67500667-55137d00-f683-11e9-9c2f-56d46e4a2fd6.png)

Thank you & good luck to the team !

**Comment by mhdawson** [comment] 2019-10-24 15:26
captured ps -ef to /root/processes-oct-24-11am so that we can compare later on.

**Comment by mhdawson** [comment] 2019-10-24 15:29
Quick view of current network traffic:

```
root@infra-digitalocean-ubuntu1604-x64-1:~# ./net.sh eth0
eth0  {rx: 30210, tx: 2227515}
eth0  {rx: 26583, tx: 2158521}
eth0  {rx: 20494, tx: 2057774}
eth0  {rx: 23532, tx: 2118576}
eth0  {rx: 30432, tx: 2243042}
```

**Comment by mhdawson** [comment] 2019-10-24 15:34
cat /proc/loadavg
2.15 1.99 1.96 4/243 29237

**Comment by renaudaste** [comment] 2019-10-24 16:00
It just worked on our CI (after a 2 minutes download) 👍👍

**Comment by mhdawson** [comment] 2019-10-24 16:19
Downloads seem to be better now. This would suggest that it's not related to CPU as we have python using a full cpu at this point and the load average is higher than when it was slower.

**Comment by mhdawson** [comment] 2019-10-24 16:21
Network traffic looks about the same as well:

```
root@infra-digitalocean-ubuntu1604-x64-1:~# sh net.sh eth0
eth0  {rx: 35296, tx: 2251919}
eth0  {rx: 30120, tx: 2168731}
eth0  {rx: 30425, tx: 2175548}
eth0  {rx: 29904, tx: 2170620}
eth0  {rx: 30850, tx: 2176010}
```

**Comment by mhdawson** [comment] 2019-10-24 16:47
Looking at the processes running when it was slow versus now.  These don't seem to be running anymore:

/usr/local/go/bin/logshare-cli
node /home/logs/log-collect/json-log-filter.js ^.*\.(tar\.xz|tar\.gz|exe|msi|pkg|7z|zip|lib|pdb|exp)(\?.*)?$
/bin/sh -c    /home/logs/log-collect/log-collect.sh
/bin/bash /home/logs/log-collect/log-collect.sh

@rvagg any chance you think those could be related?

The only other thing I can think of is that we've always had a peak in terms of download requests around these times and since 13.x is larger due the ICU data we now are saturating the network link during that time where we got away with it before.  The peak seems to be staying around ~2110000 but I think I see more intervals where it drops below that than before.

**Comment by mhdawson** [comment] 2019-10-24 19:18
To a quick look to see what the numbers look like now:

Lower network load:
```
th0  {rx: 2952, tx: 1732746}
eth0  {rx: 2204, tx: 1140427}
eth0  {rx: 3119, tx: 1375197}
eth0  {rx: 2709, tx: 1506653}
eth0  {rx: 6077, tx: 2085798}
eth0  {rx: 7269, tx: 2105457}
eth0  {rx: 4834, tx: 2036253}
eth0  {rx: 2898, tx: 1456267}
eth0  {rx: 5710, tx: 2224667}
eth0  {rx: 4258, tx: 1712641}
eth0  {rx: 3340, tx: 1657744}
```
lower load average as well:

```
cat /proc/loadavg
0.58 0.65 0.81 1/222 31659
```

**Comment by rvagg** [comment] 2019-10-25 02:39
Stats are all very tame, load average suggest hardly any effort being applied here.

I've disabled those log-collect jobs, that was the logfetch thing I've been _trying_ to get going for ages but I think I'm giving up on that approach. I doubt it's related here though.

_If_ this is a problem on our end and not some network thing, https://nodejs.org/metrics/summaries/total.png might suggest where we're running into trouble. The rate of growth of Mb/day has accelerated above the rate of growth of downloads/day, which I suppose points to the ICU change. There could be something here about the time it takes to close out a single download session leading to a higher concurrency.

I've done some system-level tweaking and changed a couple of nginx config options that might address bandwidth increase concerns. Let's see if that changes anything?

I'm still very dubious, it's a lot of traffic, but really shouldn't be enough to make our servers sweat much at all. I'd be more concerned if load average was in the ~10 range. It's difficult to see what's going on at the i/o level so _maybe_ there's something there, I just doubt it.

Anyway, more pressure to get this thing fully CDNified, as if we needed more pressure.

**Comment by mhdawson** [comment] 2019-10-25 14:50
Load today seems lower than past 2 days

```
cat /proc/loadavg
0.57 0.63 0.62 1/202 23650
```
```
root@infra-digitalocean-ubuntu1604-x64-1:~# sh net.sh eth0
eth0  {rx: 2843, tx: 1566456}
eth0  {rx: 3563, tx: 1901493}
eth0  {rx: 3656, tx: 1849576}
eth0  {rx: 2042, tx: 1089992}
eth0  {rx: 2664, tx: 1552519}
eth0  {rx: 2375, tx: 1052912}
eth0  {rx: 4914, tx: 2037342}
```

**Comment by OriginalEXE** [comment] 2019-10-29 15:10
Seems to be happening again at the moment.

**Comment by merlinnot** [comment] 2019-10-29 15:13
I can confirm that.

**Comment by shouze** [comment] 2019-10-29 15:46
or maybe some people at https://bintray.com/ @bintray (or some other competitor) would offer to host node artifacts for the sake? 💝 👼 🙏

**Comment by rvagg** [comment] 2019-10-30 01:23
Thanks for the sendfile hint @shouze, I've done that now.

Looking at the metrics in DigitalOcean these brownouts are correlated with bandwidth peaks; both CPU and I/O are not a problem. We're hitting new highs that we haven't before and I think this is the ultimate cause of our problems. I don't know where that problem lies, whether our main server or somewhere in the DigitalOcean network pipeline. Droplets are not individually constrained on bandwidth so in theory that pipeline should be fine.

Anyway, we're making good progress on getting fully CDNified. While we're thankful for suggestions, we have some constraints that don't make it as simple as just switching on full CDN for these things. But we have promising progress that should let us get there pretty soon. There's obviously some urgency with this given these outages! Will update here when we've made the transition.

Please continue let us know here if you experience outages still, it helps us correlate with other metrics to try and identify the true cause.

**Comment by bvitale** [comment] 2019-10-30 16:06
Downloads are slow again

**Comment by MattIPv4** [comment] 2019-10-30 16:11
Seeing this as an issue again

**Comment by SamChou19815** [comment] 2019-10-30 16:13
Downloads are slow again

**Comment by MattIPv4** [comment] 2019-10-30 16:25
@rvagg If there is anything we can help with on the DigitalOcean side of things, please do reach out to our support team :)

**Comment by rvagg** [comment] 2019-10-30 23:27
Yep, that's the next step, thanks @MattIPv4. We have nicer metrics now and these outages correlate with bandwidth peaks and nothing else and nothing we've done on the server seems to have made an impact.

**Comment by rvagg** [comment] 2019-10-31 01:21
Very prompt intervention from DO Support, they appear to agree that there's something odd going on at the network level, we hit a peak and it seems like a ceiling. So our primary droplet has been migrated to new hardware and we'll continue to monitor. Please let us know if problems persist. We have a peak time of day that correlates directly with the US workday, starting around 2pm UTC / 7am Pacific. Peak time lasts for roughly 4 hours from there. That's when these problems are most likely to be experienced so please let us know.

I've also tightened up the health-check in Cloudflare so it will hopefully recognise a problem quicker and shunt traffic over to our backup server. The load balancing logs don't show any problems over the last week so either our health check has been too relaxed or the problems are not experienced at the same level and maybe it's somewhere else.

@jbergstroem and I are continuing to work on better CDN fronting with some urgency.

**Comment by MylesBorins** [comment] 2019-10-31 01:58
Thanks for all the hard work on this @rvagg

**Comment by chrizzo84** [comment] 2019-10-31 05:52
Hi all, 
problem still exists... Tested on Azure DevOps Agent.
gzip: stdin: unexpected end of file
/bin/tar: Unexpected EOF in archive
/bin/tar: Unexpected EOF in archive
/bin/tar: Error is not recoverable: exiting now

**Comment by jbergstroem** [comment] 2019-11-04 19:38
Small update: we are now carefully testing a caching strategy for the most common file formats. If things proceed well (as it does seem to), we will start covering more parts of the site and be more generous with TTL's.

**Comment by rvagg** [comment] 2019-11-06 01:05
I don't believe we'll see this particular incarnation of problems with nodejs.org from now on. Future problems are likely to be of a different nature, so I'm closing this issue.

We're now fully fronting our downloads with CDN and it appears to be working well. It's taken considerable load off our backend servers of course and we're unlikely to hit the bandwidth peaks at the network interface that appears to have been a problem previously.

Primary server bandwidth:

<img width="474" alt="Screenshot 2019-11-06 12 02 39" src="https://user-images.githubusercontent.com/495647/68259302-95b0c480-008d-11ea-8cea-0ab004130d43.png">

Cloudflare caching:

<img width="1202" alt="Screenshot 2019-11-06 12 01 35" src="https://user-images.githubusercontent.com/495647/68259301-95182e00-008d-11ea-83b9-e4f321ab4ae5.png">

**Closed by rvagg** 2019-11-06 01:05 UTC

**Comment by OriginalEXE** [comment] 2019-11-06 10:56
Thank you to everyone for their hard work, sending virtual :hugs:.

**Comment by matsaman** [comment] 2019-11-20 20:04
Apparently encountering this type of issue still. For the past two days I get around a 20% failure rate consistently:

```
$ for i in {01..10}; do echo "$i"' '"$(date -u)"; curl https://nodejs.org/dist/v12.13.1/node-v12.13.1-linux-x64.tar.xz -o node-v12.13.1-linux-x64.tar.xz; done
01 Wed Nov 20 19:46:43 UTC 2019
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.4M  100 13.4M    0     0   217k      0  0:01:03  0:01:03 --:--:-- 1620k
02 Wed Nov 20 19:47:46 UTC 2019
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.4M  100 13.4M    0     0  4237k      0  0:00:03  0:00:03 --:--:-- 4236k
03 Wed Nov 20 19:47:49 UTC 2019
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.4M  100 13.4M    0     0  1651k      0  0:00:08  0:00:08 --:--:-- 1247k
04 Wed Nov 20 19:47:57 UTC 2019
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 62 13.4M   62 8527k    0     0  28569      0  0:08:12  0:05:05  0:03:07 19759
curl: (18) transfer closed with 5335120 bytes remaining to read
05 Wed Nov 20 19:53:02 UTC 2019
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.4M  100 13.4M    0     0  3489k      0  0:00:03  0:00:03 --:--:-- 3488k
06 Wed Nov 20 19:53:06 UTC 2019
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 83 13.4M   83 11.2M    0     0  25695      0  0:09:07  0:07:39  0:01:28 19389
curl: (18) transfer closed with 2255352 bytes remaining to read
07 Wed Nov 20 20:00:46 UTC 2019
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.4M  100 13.4M    0     0  4398k      0  0:00:03  0:00:03 --:--:-- 4398k
08 Wed Nov 20 20:00:49 UTC 2019
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.4M  100 13.4M    0     0  2798k      0  0:00:04  0:00:04 --:--:-- 2798k
09 Wed Nov 20 20:00:54 UTC 2019
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.4M  100 13.4M    0     0  2340k      0  0:00:05  0:00:05 --:--:-- 2282k
10 Wed Nov 20 20:01:00 UTC 2019
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.4M  100 13.4M    0     0  2149k      0  0:00:06  0:00:06 --:--:-- 2197k
```

**Comment by rvagg** [comment] 2019-11-21 05:14
Where are you @matsaman? could be a cloudflare problem in your region. See https://www.cloudflarestatus.com/ and check whether one of the edges close to you is having trouble. Without further reports of problems or something we can reproduce ourselves our best guess is going to be that it's a problem somewhere between Cloudflare and your computer since CF should have it cached.

**Comment by matsaman** [comment] 2019-11-22 19:06
Items on that page in my region say 'Operational' at this time. Should I encounter the issue again I will check that page after my tests and include my findings here.

**Comment by appu24** [comment] 2020-01-14 09:04
Hi,

![image](https://user-images.githubusercontent.com/14196578/72329334-f97aed80-36cd-11ea-9948-baafef0942c9.png)

I am still facing this problem on Azure DevOps.
Do we have a fix for this by any chance?

Thanks in advance.

**Comment by mhdawson** [comment] 2020-01-14 15:00
I'm getting fast downloads.  Please open a new issue if you believe there is still a problem versus commenting on this close issue.

**Comment by rvagg** [comment] 2020-01-14 23:31
@appu24 tar failure doesn't necessarily indicate a download error. Are you able to get more log output for that to see exactly what it's failing on. I would assume something in the chain is generating some stderr logging at least.

**Comment by tbsvttr** [comment] 2023-08-21 12:24
very slow download for me

**Comment by saschanos** [comment] 2023-08-30 13:47
Experiencing issues for weeks now; from different IPs and servers. Is there any known reason for this?

**Comment by MattIPv4** [comment] 2023-08-30 13:51
> Is there any known reason for this?

Yes, the origin server is being overloaded with traffic, in part due to every release of Node.js purging the Cloudflare cache for the entire domain.

There are a bunch of issues open that aim to help rectify this:

- https://github.com/nodejs/build/issues/3473 (fix some edge cases bypassing the cache currently)
- https://github.com/nodejs/build/issues/3461 (replace the overwhelmed origin with Cloudflare R2)
- https://github.com/nodejs/build/issues/3439 (disallow folks bypassing Cloudflare cache and hitting the origin directly)
- https://github.com/nodejs/build/issues/3424 (meta issue for the overwhelmed origin as it is currently)
- https://github.com/nodejs/build/issues/3410 (changing how cache purges happen for releases so the entire cache isn't wiped)

**Comment by hellmediadev** [comment] 2023-09-27 14:05
nodejs.org file delivery is currently not working again. This might be a working mirror: 
https://mirrors.cloud.tencent.com/nodejs-release/

**Comment by stevenmettler** [comment] 2023-10-25 13:26
Hi there, can't download node. Continued "Failed - Network Error" from my mac
