### ISSUE TITLE
High number of 404s downloading node in our CI environment

### ISSUE THREAD

**Issue by gmishkin** [nodejs/build#3227] opened 2023-03-16 14:35 UTC
URL in our case: https://nodejs.org/dist/v16.18.0/node-v16.18.0-linux-x64.tar.xz

I came here and saw #3224 and the timing lines up with when we started noticing it about an hour ago.

Update: now seeing some `522` status codes

**Comment by nschonni** [comment] 2023-03-17 00:14
This is probably a better repo, but follow https://github.com/nodejs/nodejs.org/issues/5149 as that is were the updates are going

**Comment by tniessen** [comment] 2023-03-17 00:21
https://status.nodejs.org/

**Comment by ovflowd** [comment] 2023-03-17 09:10
Duplicate of #5149.

**Closed** 2023-03-17 09:16 UTC
Labels: incident
